### ISSUE TITLE
Flutter_quill version 8.1.1 Invalid argument(s): Could not find the default tooltip for Attribute{key: direction, scope: AttributeScope.BLOCK

### ISSUE THREAD

**Issue by salba360496** [singerdmx/flutter-quill#1490] opened 2023-10-30 05:14 UTC
My issue is about [Mobile]
the issue is caused if 

**QuillToolbar(configurations: QuillToolbarConfigurations(showDirection: true)),**

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞══════════════════════
The following ArgumentError was thrown building<…>
QuillToolbarToggleStyleButton(dirty, dependencies:<…>
[QuillToolbarProvider], state:<…>
_QuillToolbarToggleStyleButtonState#a8586):<…>
Invalid argument(s): Could not find the default tooltip for<…>
Attribute{key: direction, scope: AttributeScope.BLOCK, value:<…
rtl}<…>
<…>
The relevant error-causing widget was:<…>
  QuillToolbar<…>

**Comment by salba360496** [comment] 2023-10-30 16:54
quick fix for now 
QuillToolbar(configurations: QuillToolbarConfigurations( buttonOptions: QuillToolbarButtonOptions(direction: QuillToolbarToggleStyleButtonOptions(tooltip: 'Direction', iconData: Icons.format_textdirection_r_to_l)),
showDirection: true))

**Comment by freshtechtips** [comment] 2023-10-31 19:55
> My issue is about [Mobile] the issue is caused if
> 
> **QuillToolbar(configurations: QuillToolbarConfigurations(showDirection: true)),**
> 
> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞══════════════════════ The following ArgumentError was thrown building<…> QuillToolbarToggleStyleButton(dirty, dependencies:<…> [QuillToolbarProvider], state:<…> _QuillToolbarToggleStyleButtonState#a8586):<…> Invalid argument(s): Could not find the default tooltip for<…> Attribute{key: direction, scope: AttributeScope.BLOCK, value:<… rtl}<…> <…> The relevant error-causing widget was:<…> QuillToolbar<…>

Hi, thank you for the report, please consider sending more information on how to get this issue and more information on what are you trying to do and the version you are using

**Comment by salba360496** [comment] 2023-11-01 09:15
Flutter_quill version 8.1.1
when I try to add a direction button without overriding QuillToolbarToggleStyleButtonOptions(tooltip: 'Direction', iconData: Icons.format_textdirection_r_to_l)),
the package does not find the tooltip. and icon of the direction button.

**Comment by freshtechtips** [comment] 2023-11-05 00:50
> Flutter_quill version 8.1.1 when I try to add a direction button without overriding QuillToolbarToggleStyleButtonOptions(tooltip: 'Direction', iconData: Icons.format_textdirection_r_to_l)), the package does not find the tooltip. and icon of the direction button.

I'm late but now I'm able to encounter the issue, give us some time and it will be fixed soon.

**Comment by freshtechtips** [comment] 2023-11-05 01:02
> Flutter_quill version 8.1.1 when I try to add a direction button without overriding QuillToolbarToggleStyleButtonOptions(tooltip: 'Direction', iconData: Icons.format_textdirection_r_to_l)), the package does not find the tooltip. and icon of the direction button.

The issue is fixed in this [commit](https://github.com/singerdmx/flutter-quill/commit/69c8b22e9422dd408b807489fe0ff3a1dfcce64a)

You will get the fix in version `8.1.11`

If you still have any other issues or questions, feel free to ask us at anytime.

**Closed by freshtechtips** 2023-11-05 01:02 UTC
