### ISSUE TITLE
[Mobile] Difficulty positioning the cursor

### ISSUE THREAD

**Issue by matthiasn** [singerdmx/flutter-quill#480] opened 2021-11-25 07:24 UTC
Normally on iOS when trying to move the cursor in a text, the position within a word is show above my finger, such as in the Notes app on iOS 15:

![image](https://user-images.githubusercontent.com/1390808/143396261-acdf1cb3-bf46-4863-910a-2eece66f9063.png)

With this library, however, the cursor completely disappears under my index finger, turning the attempt to edit a word into guesswork and making me feel clumsy. 

I also tested with the latest version of the example app (on an iPhone 12 Pro), and it is the same behavior there.

**Comment by singerdmx** [comment] 2021-11-30 03:11
It may be caused by https://github.com/singerdmx/flutter-quill/commit/6f8624e3afb87647c61c00e76562e9483686b2cc
Not entirely sure.
Need to look into it further.

**Comment by MagTuxGit** [comment] 2021-12-10 16:57
v 2.3.0
Something weird happening to the iOS floating cursor.
https://user-images.githubusercontent.com/5296407/145611398-046a24c3-1e08-48b1-8bf3-ace46cd4f264.mov
Is it still in progress?

**Comment by singerdmx** [comment] 2021-12-10 16:58
No.
I guess we need to fix it

**Comment by singerdmx** [comment] 2021-12-10 16:59
Bug should be introduced by https://github.com/singerdmx/flutter-quill/commit/13d542680e538f7efa0d88b152ef4b2b96f597a3

**Comment by MagTuxGit** [comment] 2021-12-10 17:02
> Bug should be introduced by [13d5426](https://github.com/singerdmx/flutter-quill/commit/13d542680e538f7efa0d88b152ef4b2b96f597a3)

Before this moving cursor with Space button was not allowed at all.

**Comment by bugrevealingbme** [comment] 2022-08-14 20:37
This problem also exists on Android and it is very frustrating. Can you speed it up please?

**Comment by NicoEssi** [comment] 2023-09-15 08:17
> https://youtu.be/YBRkVCRP1Gw
> 
> Will this be helpful？

Looks promising. How can I implement the RawMagnifier widget into the editor?

**Comment by freshtechtips** [comment] 2023-11-08 18:05
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.

**Closed by freshtechtips** 2023-11-08 18:05 UTC
