### ISSUE TITLE
[Mobile] `select all` cannot trigger the `Copy`

### ISSUE THREAD

**Issue by Allenxuxu** [singerdmx/flutter-quill#925] opened 2022-08-26 13:58 UTC
flutter_quill: ^4.2.3
Flutter SDK version: 2.10.3 

In the read only mode, after `select all` cannot trigger the `Copy` in real machine，but it is ok for the simulator.

**Comment by YugoMatsuda** [comment] 2022-09-13 08:20
Thank you for  great tool.
I reproduced this problem too.
I was able to select all and copy the short sentences, but It can not be done if it's a long sentence.

'short sentences'
https://user-images.githubusercontent.com/61716314/189849237-ff31d763-9a08-4285-9307-02754fd5a0f0.mp4

'long sentences'
https://user-images.githubusercontent.com/61716314/189849388-6be65518-6722-4b7d-8ac2-bb547326b456.mp4

**Comment by Heyholder** [comment] 2022-12-30 01:45
did you fix it? I have same problem.

**Comment by freshtechtips** [comment] 2023-11-08 18:13
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.

**Closed by freshtechtips** 2023-11-08 18:13 UTC
