### ISSUE TITLE
how to get First image link from QuillEditor  ?

### ISSUE THREAD

**Issue by MaheshManoharan** [singerdmx/flutter-quill#36] opened 2021-02-21 13:35 UTC
Hi, I just want to get the first image link from the data that the user entered in quillEditor. My app stores images in device storage using the path provider package.  I printed the data and got this `insert⟨ {image: /data/user/0/com.example.notes/app_flutter/image_picker8603960138221828112.jpg} ⟩`

but don't know how to get the first image link from this line. is there any idea?

**Comment by singerdmx** [comment] 2021-02-21 13:38
Check out https://github.com/singerdmx/flutter-quill/issues/20

**Comment by singerdmx** [comment] 2021-02-21 13:40
Checkout https://github.com/singerdmx/flutter-quill/issues/12

**Comment by MaheshManoharan** [comment] 2021-02-21 13:48
I copied the image into a different folder from device storage in App. Image is showing fine and the image link is fine. But actually I don't know how to get image link when the save button is pressed.

**Comment by MaheshManoharan** [comment] 2021-02-21 13:49
Do I need to extract the image link from the Json ?

**Comment by singerdmx** [comment] 2021-02-21 13:50
I assume you do not upload image every time but only during pressing save button?

**Comment by singerdmx** [comment] 2021-02-21 13:52
I guess you are doing local image way which is similar to what @ArjanAswal is doing

**Comment by singerdmx** [comment] 2021-02-21 13:53
> Do I need to extract the image link from the Json ?

If you are doing local image way, yeah, you probably need to scan the json body for local image url and then upload them

**Comment by MaheshManoharan** [comment] 2021-02-21 13:53
Yes. 
Future<String> _uploadImageCallBack(File file) async {
    // call upload file API and return file's absolute url
    File tmpFile = File(file.path);

    final appDir = await getApplicationDocumentsDirectory();

    final fileName = basename(tmpFile.path);

    tmpFile = await tmpFile.copy('${appDir.path}/$fileName');

    var completer = new Completer<String>();
    completer.complete('${tmpFile.path}');
    return completer.future;
  }

**Comment by singerdmx** [comment] 2021-02-21 13:55
OK, you plan to upload the images, right?

**Comment by MaheshManoharan** [comment] 2021-02-21 13:55
No, no need to upload images.

**Comment by MaheshManoharan** [comment] 2021-02-21 13:55
Image is always on the local storage.

**Comment by singerdmx** [comment] 2021-02-21 13:57
Then when pressing Save button, what do you need to do?

**Comment by MaheshManoharan** [comment] 2021-02-21 13:57
I use a save button, when the user write note successfully. user will tap on save button. While I get data from quill editor, at that time, how I get first image local storage link from that data?

**Comment by ArjanAswal** [comment] 2021-02-21 13:59
@singerdmx the local image gets picked by the image picker extension and gets copied into temporary directory. The problem is that temporary directory cache can get cleared anytime so the image might not be rendered in the editor. How about we use application directory instead?

**Comment by singerdmx** [comment] 2021-02-21 13:59
> how I get first image local storage link from that data?

you probably need to scan the json of delta

**Comment by ArjanAswal** [comment] 2021-02-21 14:00
> I use a save button, when the user write note successfully. user will tap on save button. While I get data from quill editor, at that time, how I get first image local storage link from that data?

You can use regex on delta. Or take the data from the upload image callback.

**Comment by singerdmx** [comment] 2021-02-21 14:00
@ArjanAswal is that sth decided by image picker?

**Comment by singerdmx** [comment] 2021-02-21 14:01
> How about we use application directory instead?

I have no objection to that. Just how

**Comment by MaheshManoharan** [comment] 2021-02-21 14:02
regex? no, if I take image from callback. If user deleted that image in editor. that wont be a good one i think.

**Comment by ArjanAswal** [comment] 2021-02-21 14:04
> @ArjanAswal is that sth decided by image picker?

Yes thats true. What can we do about it?
If a user opens the editor after a long time and the cache gets cleared... we lose the image as well. 
We can copy the file path from the temporary directory to the application directory and return that instead.

**Comment by MaheshManoharan** [comment] 2021-02-21 14:04
I need to scan json data. as a beginner, I don't know how to do that? is there any tutorial or what to search in google, that would be helpful to me.

**Comment by ArjanAswal** [comment] 2021-02-21 14:06
> If user deleted that image in editor. that wont be a good one i think.

That is why you can use regex to get the image from the final document.

**Comment by MaheshManoharan** [comment] 2021-02-21 14:06
@ArjanAswal I faced that cache problem earlier.

**Comment by singerdmx** [comment] 2021-02-21 14:07
@MaheshManoharan I don't think you have to deal with json. `_controller.document.toDelta().toList()` gives `List<Operation>`. Just iterate that

**Comment by ArjanAswal** [comment] 2021-02-21 14:10
> > How about we use application directory instead?
> 
> I have no objection to that. Just how

Copy the file from temporary directory to the applications directory, and return that instead.

**Comment by singerdmx** [comment] 2021-02-21 14:11
> Copy the file from temporary directory to the applications directory, and return that instead.

Don't you do that in the callback?

**Comment by ArjanAswal** [comment] 2021-02-21 14:12
> > Copy the file from temporary directory to the applications directory, and return that instead.
> 
> Don't you do that in the callback?

Sure, but should we make this clear in readme?

**Comment by MaheshManoharan** [comment] 2021-02-21 14:15
I got this when I iterate through the data.

` insert⟨ {image: /data/user/0/com.example.notes/app_flutter/image_picker8603960138221828112.jpg} ⟩`

how to extract image link only... Sorry I am a beginner.

**Comment by singerdmx** [comment] 2021-02-21 14:16
Here is what I think we should do

![image](https://user-images.githubusercontent.com/122956/108627763-1d018300-740c-11eb-94fb-e1534bc3996d.png)


1. Rename `uploadFileCallback` to `onImageTapCallBack`
2. In app/lib/pages/home_page.dart, provide a second callback example - your example

**Comment by ArjanAswal** [comment] 2021-02-21 14:18
> I got this when I iterate through the data.
> 
> ` insert⟨ {image: /data/user/0/com.example.notes/app_flutter/image_picker8603960138221828112.jpg} ⟩`
> 
> how to extract image link only... Sorry I am a beginner.

Now use regex on this to extract the link.
Or even simply just slice the string from 13, -2

**Comment by singerdmx** [comment] 2021-02-21 14:18
> how to extract image link only.

```
if op.key == 'insert' && op.data is Embeddable
```

**Comment by ArjanAswal** [comment] 2021-02-21 14:19
> Here is what I think we should do
> 
> ![image](https://user-images.githubusercontent.com/122956/108627763-1d018300-740c-11eb-94fb-e1534bc3996d.png)
> 
> 
> 1. Rename `uploadFileCallback` to `onImageTapCallBack`
> 2. In app/lib/pages/home_page.dart, provide a second callback example - your example

Looks good to me👍

**Comment by singerdmx** [comment] 2021-02-21 14:20
@ArjanAswal let me do #1 then can you do #2 ?

**Comment by ArjanAswal** [comment] 2021-02-21 14:21
> @ArjanAswal let me do #1 then can you do #2 ?

Sure

**Comment by MaheshManoharan** [comment] 2021-02-21 14:22
<img width="475" alt="adb" src="https://user-images.githubusercontent.com/69787389/108627994-507cf580-747e-11eb-8e72-1ddcdca26c7b.png">

how to use regex here.

**Comment by ArjanAswal** [comment] 2021-02-21 14:24
> <img width="475" alt="adb" src="https://user-images.githubusercontent.com/69787389/108627994-507cf580-747e-11eb-8e72-1ddcdca26c7b.png">
> 
> how to use regex here.  

No need. See @singerdmx answer.

**Comment by MaheshManoharan** [comment] 2021-02-21 14:27
@ArjanAswal  I don't get it. Which answer

**Comment by ArjanAswal** [comment] 2021-02-21 14:28
> @ArjanAswal  I don't get it. Which answer

[this](https://github.com/singerdmx/flutter-quill/issues/36#issuecomment-782865276)

**Comment by MaheshManoharan** [comment] 2021-02-21 14:29
@ArjanAswal  Where to use that? and what is op?

**Comment by ArjanAswal** [comment] 2021-02-21 14:31
> @ArjanAswal  Where to use that? and what is op?

op is just a parameter name used in a forEach loop.
Op is The iterated list item.

**Comment by singerdmx** [comment] 2021-02-21 14:32
`_controller.document.toDelta().toList()` gives `List<Operation>`. Just iterate that and 

```
for op in _controller.document.toDelta().toList() {
  if (op.key == 'insert' && op.data is Embeddable) {
     Embeddable embeddable = op.data as Embeddable;
     // check embeddable.type
     final imageUrl = embeddable.data;
  }
}
```

**Comment by singerdmx** [comment] 2021-02-21 14:34
@ArjanAswal  submitted https://github.com/singerdmx/flutter-quill/commit/d644223bb3574f86d39dd4b4d9d67c8b69a24e83

Please do #2

**Comment by MaheshManoharan** [comment] 2021-02-21 14:39
@singerdmx I got Embeddable not defined error. Is there any package I need to import?

**Comment by singerdmx** [comment] 2021-02-21 14:40
@ArjanAswal  sorry, one more https://github.com/singerdmx/flutter-quill/commit/4f044e2b0925634199442f98930ca8f3760ec306

**Comment by singerdmx** [comment] 2021-02-21 14:43
> @singerdmx I got Embeddable not defined error. Is there any package I need to import?

```
import 'package:flutter_quill/models/documents/nodes/embed.dart';
```

**Comment by ArjanAswal** [comment] 2021-02-21 14:46
@singerdmx Should I delete the._fakeuploadimagecallback function or keep it?
Also do I have to commit in stable branch?

**Comment by singerdmx** [comment] 2021-02-21 14:48
Keep _fakeuploadimagecallback even though it is not referenced

Yes, stable branch - I will cherry pick to master

**Comment by singerdmx** [comment] 2021-02-21 14:49
> Keep _fakeuploadimagecallback even though it is not referenced

Please add comments referencing _fakeuploadimagecallback

**Comment by singerdmx** [comment] 2021-02-21 14:50
On second thought, delete _fakeuploadimagecallback but add comments mentioning one can instead `Upload the image file to AWS s3 when image is picked`

**Comment by ArjanAswal** [comment] 2021-02-21 15:09
@singerdmx check out the latest commit

**Comment by singerdmx** [comment] 2021-02-21 15:16
nice, do you have this error?

![image](https://user-images.githubusercontent.com/122956/108629437-b7fe5b00-7414-11eb-8991-d3d87a01436e.png)

**Comment by singerdmx** [comment] 2021-02-21 15:21
Fixed by https://github.com/singerdmx/flutter-quill/commit/209983746552a1672b95834634b9d4652e4974bf

**Comment by singerdmx** [comment] 2021-02-21 15:21
OK, I am closing this

**Closed by singerdmx** 2021-02-21 15:21 UTC

**Comment by MaheshManoharan** [comment] 2021-02-22 02:19
`   var list = _controller.document.toDelta().toList();

        for (var op in list) {
          // print(op.key);
          // print(op.data.toString());

          Embeddable embeddable = op.data as Embeddable;

          print(embeddable.type.toString);
`


@singerdmx When I use this code to print the image link, I got this error **type 'String' is not a subtype of type 'Embeddable' in type cast**

**Comment by singerdmx** [comment] 2021-02-22 02:20
Man, can u copy the whole code?

for op in _controller.document.toDelta().toList() {
  if (op.key == 'insert' && op.data is Embeddable) {
     Embeddable embeddable = op.data as Embeddable;
     // check embeddable.type and it should be 'image'
     final imageUrl = embeddable.data;
  }
}

**Comment by MaheshManoharan** [comment] 2021-02-22 02:35
`        var list = _controller.document.toDelta().toList();
        print('inside onpressed');
        for (var op in list) {
          print("inside for loop");

          if (op.key == 'insert' && op.data is Embeddable) {
            print('inside if loop');
            Embeddable embeddable = op.data as Embeddable;

            if (embeddable.type == "image") {
              final imageUrl = embeddable.data;
              print(imageUrl);
            }
          }
        }
`

Yes. I did. ..execution not entering in if loop.

**Comment by ArjanAswal** [comment] 2021-02-22 04:34
> `        var list = _controller.document.toDelta().toList();
>         print('inside onpressed');
>         for (var op in list) {
>           print("inside for loop");
> 
>           if (op.key == 'insert' && op.data is Embeddable) {
>             print('inside if loop');
>             Embeddable embeddable = op.data as Embeddable;
> 
>             if (embeddable.type == "image") {
>               final imageUrl = embeddable.data;
>               print(imageUrl);
>             }
>           }
>         }
> `
> @singerdmx , @ArjanAswal 
> Yes. I did. ..execution not entering in if loop. 

Use regex in `controller.document.toDelta().toString()` to extract the link.

**Comment by ArjanAswal** [comment] 2021-02-22 04:36
> > `        var list = _controller.document.toDelta().toList();
> >         print('inside onpressed');
> >         for (var op in list) {
> >           print("inside for loop");
> > 
> >           if (op.key == 'insert' && op.data is Embeddable) {
> >             print('inside if loop');
> >             Embeddable embeddable = op.data as Embeddable;
> > 
> >             if (embeddable.type == "image") {
> >               final imageUrl = embeddable.data;
> >               print(imageUrl);
> >             }
> >           }
> >         }
> > `
> > @singerdmx , @ArjanAswal 
> > Yes. I did. ..execution not entering in if loop. 
> 
> Use regex in `controller.document.toDelta().toString()` to extract the link.

This isn't a clean solution, and should only be used temporarily.

**Comment by MaheshManoharan** [comment] 2021-02-24 12:08
Thank you both @singerdmx , @ArjanAswal  regex worked.

**Comment by rikai-trongpq** [comment] 2022-02-23 03:50
@singerdmx 
```
for op in _controller.document.toDelta().toList() {
if (op.key == 'insert' && op.data is Embeddable) {
Embeddable embeddable = op.data as Embeddable;
// check embeddable.type and it should be 'image'
final imageUrl = embeddable.data;
}
}
```
This code is have problem. You are check `op.data is Embeddable` before you cast `op.data` to Embeddable`?
