### ISSUE TITLE
Custom buttons are not showing with QuillBaseToolbarConfigurations in Flutter

### ISSUE THREAD

**Issue by singhmukesh2023** [singerdmx/flutter-quill#1497] opened 2023-11-01 08:31 UTC
I am creating a custom Toolbar with some existing features of library. All button(Bold, Italic, Underling, lists) of childrenBuilder section are showing, but buttons of custom buttons are not showing.

```dart

     Widget _getCustomToolbar() {
        return QuillToolbarProvider(
          toolbarConfigurations: const QuillToolbarConfigurations(),
          child: QuillBaseToolbar(
              configurations: QuillBaseToolbarConfigurations(
                  toolbarSize: 20 * 2,
                  multiRowsDisplay: false,
                  childrenBuilder: (context) {
                    final controller = context.requireQuillController;
                    return [
                      QuillToolbarToggleStyleButton(
                        attribute: Attribute.bold,
                        controller: controller,
                        options: const QuillToolbarToggleStyleButtonOptions(
                          iconData: Icons.format_bold,
                          iconSize: 20,
                        ),
                      ),
                      QuillToolbarToggleStyleButton(
                        attribute: Attribute.italic,
                        controller: controller,
                        options: const QuillToolbarToggleStyleButtonOptions(
                          iconData: Icons.format_italic,
                          iconSize: 20,
                        ),
                      ),
                      QuillToolbarToggleStyleButton(
                        attribute: Attribute.underline,
                        controller: controller,
                        options: const QuillToolbarToggleStyleButtonOptions(
                          iconData: Icons.format_underline,
                          iconSize: 20,
                        ),
                      ),
                      QuillToolbarToggleStyleButton(
                        attribute: Attribute.ol,
                        controller: controller,
                        options: const QuillToolbarToggleStyleButtonOptions(
                          iconData: Icons.format_list_numbered,
                          iconSize: 20,
                        ),
                      ),
                      QuillToolbarToggleStyleButton(
                        attribute: Attribute.ul,
                        controller: controller,
                        options: const QuillToolbarToggleStyleButtonOptions(
                          iconData: Icons.format_list_bulleted,
                          iconSize: 20,
                        ),
                      ),
                    ];
                  },
                  customButtons: [
                QuillCustomButton(
                  iconData: Icons.ac_unit,
                  onTap: () {
                    debugPrint('snowflake1');
                  },
                ),
              ])),
        );
      }

**Comment by freshtechtips** [comment] 2023-11-03 23:33
Hi, the `QuillToolbarProvider` is designed for the `QuillToolbar`

When using custom toolbar, you will get the custom buttons provider in the widget tree and you can easily access it using the context, you should manually place the custom buttons in your custom toolbar, you will get a List<Widget>

The way to get them

```dart
context.requireQuillToolbarConfigurations.customButtons
```
However it's better to move the custom buttons in the `QuillToolbarProvider` where you will find `QuillToolbarConfigurations` instead of `QuillBaseToolbarConfigurations` but that is up to you

example of what it will be:

```dart
Widget _getCustomToolbar() {
    return QuillToolbarProvider(
      toolbarConfigurations: QuillToolbarConfigurations(
        customButtons: [
          QuillCustomButton(
            iconData: Icons.ac_unit,
            onTap: () {
              debugPrint('snowflake1');
            },
          ),
        ],
      ),
      child: QuillBaseToolbar(
        configurations: QuillBaseToolbarConfigurations(
          toolbarSize: 20 * 2,
          multiRowsDisplay: false,
          // customButtons: [
          //   QuillCustomButton(
          //     iconData: Icons.ac_unit,
          //     onTap: () {
          //       debugPrint('snowflake1');
          //     },
          //   ),
          // ],
          childrenBuilder: (context) {
            final controller = context.requireQuillController;
            // final quillBaseToolbarConfigurations =
            //     QuillBaseToolbarProvider.ofNotNull(context)
            //         .toolbarConfigurations;
            return [
              for (final customButton
                  in context.requireQuillToolbarConfigurations.customButtons)
                if (customButton.child != null) ...[
                  InkWell(
                    onTap: customButton.onTap,
                    child: customButton.child,
                  ),
                ] else ...[
                  CustomButton(
                    onPressed: customButton.onTap,
                    icon: customButton.iconData ??
                        context.quillToolbarBaseButtonOptions?.iconData,
                    iconColor: customButton.iconColor,
                    iconSize: customButton.iconSize ?? 18, // default font size
                    iconTheme:
                        context.requireQuillToolbarBaseButtonOptions.iconTheme,
                    afterButtonPressed: customButton.afterButtonPressed ??
                        context
                            .quillToolbarBaseButtonOptions?.afterButtonPressed,
                    tooltip: customButton.tooltip ??
                        context.quillToolbarBaseButtonOptions?.tooltip,
                  ),
                ],
              QuillToolbarToggleStyleButton(
                attribute: Attribute.bold,
                controller: controller,
                options: const QuillToolbarToggleStyleButtonOptions(
                  iconData: Icons.format_bold,
                  iconSize: 20,
                ),
              ),
              QuillToolbarToggleStyleButton(
                attribute: Attribute.italic,
                controller: controller,
                options: const QuillToolbarToggleStyleButtonOptions(
                  iconData: Icons.format_italic,
                  iconSize: 20,
                ),
              ),
              QuillToolbarToggleStyleButton(
                attribute: Attribute.underline,
                controller: controller,
                options: const QuillToolbarToggleStyleButtonOptions(
                  iconData: Icons.format_underline,
                  iconSize: 20,
                ),
              ),
              QuillToolbarToggleStyleButton(
                attribute: Attribute.ol,
                controller: controller,
                options: const QuillToolbarToggleStyleButtonOptions(
                  iconData: Icons.format_list_numbered,
                  iconSize: 20,
                ),
              ),
              QuillToolbarToggleStyleButton(
                attribute: Attribute.ul,
                controller: controller,
                options: const QuillToolbarToggleStyleButtonOptions(
                  iconData: Icons.format_list_bulleted,
                  iconSize: 20,
                ),
              ),
            ];
          },
        ),
      ),
    );
  }
```

**Comment by freshtechtips** [comment] 2023-11-04 15:49
The issue is now fixed

If you still facing this issue or have any other questions, feel free to ask us on GitHub

**Closed by freshtechtips** 2023-11-04 15:49 UTC
