### ISSUE TITLE
editor in SingleChildScrollView: text not visible 

### ISSUE THREAD

**Issue by gradus0** [singerdmx/flutter-quill#1580] opened 2023-12-09 15:09 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I use multiple text editors on one page, and the height of these text editors is dynamic.
Problem: The text is hidden behind the keyboard, and it is not visible what is being typed. If I apply the following code:

```dart
SingleChildScrollView(
    reverse: true,
    scrollDirection: Axis.vertical,
```

Then, with long text, when tapping on the first line, the scroll jumps significantly and goes much lower, and again it is not visible what is being typed, but from the top.

**Comment by singerdmx** [comment] 2023-12-09 15:09
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by Mmisiek** [comment] 2023-12-31 23:08
This is duplicate of some other Ticket.

**Closed** 2024-09-21 04:38 UTC
Labels: help wanted
