### ISSUE TITLE
 [Mobile] ios  The cursor cannot focus until the last character

### ISSUE THREAD

**Issue by dt-wonder** [singerdmx/flutter-quill#1074] opened 2023-02-01 01:53 UTC
[Mobile]
flutter 3.7
flutter_quill 6.3.1

The cursor cannot focus until the last character 

Ios has this problem, android doesn't have it, it's in Chinese, and it doesn't have it in English

**Comment by nrikiji** [comment] 2023-02-10 04:27
me too...

**Comment by im-x** [comment] 2023-02-21 05:50
me too...

**Comment by dt-wonder** [comment] 2023-02-21 05:51
@singerdmx

**Comment by CatHood0** [comment] 2024-09-22 08:00
Does this issue still persists? I think this was fixed since was mentioned into a PR. I will close it by the moment. Please reopen if the issues can be reproduced into the current version of the package.

**Closed by CatHood0** 2024-09-22 08:00 UTC
Labels: bug
