### ISSUE TITLE
[Mobile] or [Desktop]: Undo errors

### ISSUE THREAD

**Issue by Alspb** [singerdmx/flutter-quill#1289] opened 2023-07-01 09:21 UTC
The issue is about [Mobile] and [Desktop]

Pressing "Undo" might crash the app with
`type 'Null' is not a subtype of type 'Block' in type cast`
error.
Steps to reproduce on mobile:

1. Run an app with "Empty asset" initial content
2. Move the cursor to the end of the text, press "Enter"
3. Enter "Test text"
4. Move the cursor to the beginning of the text
5. Click undo (sometimes 2-3 times)

Also, undo doesn't care about the cursor position:
1. Run an app with "Empty asset" initial content
2. Remove "Empty asset" text
3. Enter two lines of text: "Line one" and "Line two"
4. Remove "two" word
5. Move the cursor to the end of the first line.
6. Press "Undo"
7. The cursor moves to the place after "Li" on the second line

**Comment by singerdmx** [comment] 2023-07-13 01:07
Will take a look

**Comment by WWLy** [comment] 2023-07-17 11:20
<img width="711" alt="截屏2023-07-17 19 19 41" src="https://github.com/singerdmx/flutter-quill/assets/16476388/429a52c0-10a0-4de9-b7af-5fa09c5267f3">
'res.node' can be null, so 'res.node as Block' will crash

**Comment by li3317** [comment] 2023-07-17 21:38
Hello, I believe this is due to incorrect positioning of the cursor when undo is triggered. We'll look into this.

**Comment by li3317** [comment] 2023-07-18 01:07
Hello, we're not able to reliably reproduce this issue, but I believe it's related to the cursor being positioned incorrectly. We'll look into it more but closing this issue for now. Thanks.

**Closed by li3317** 2023-07-18 01:07 UTC

**Comment by dsyrstad** [comment] 2023-07-18 13:37
@li3317 I have this exact same error when running in my app (web and mobile). I'm unable to reproduce it in the example app, but I am able to reproduce it consistently in my app.

**Comment by singerdmx** [comment] 2023-07-18 14:06
Sorry we can't help it

**Comment by trongnhan136** [comment] 2023-07-19 12:19
undo doesn't care about cursor position anyway (which might cause the crash described).

Need find away to keep cursor position + undo object together.

**Comment by trongnhantaisacventoan** [comment] 2023-07-20 03:09
Maybe work

```
void _handleHistoryChange(int? len) {
    if (len != null && len != 0) {
      final newOffset = len;
      if (newOffset >= document.length || newOffset < 0) {
        updateSelection(TextSelection.collapsed(offset: document.length),
            ChangeSource.LOCAL);
      } else {
        updateSelection(
            TextSelection.collapsed(offset: newOffset), ChangeSource.LOCAL);
      }
    } else {
      if (selection.baseOffset >= document.length) {
      //  make sure not overflow selection
        updateSelection(TextSelection.collapsed(offset: document.length),
            ChangeSource.LOCAL);
      }
      notifyListeners();
    }
  }


HistoryChanged _change(Document doc, List<Delta> source, List<Delta> dest) {
    if (source.isEmpty) {
      return const HistoryChanged(false, 0);
    }
    final delta = source.removeLast();
    // look for insert or delete
    final ops = delta.toList();
    int? mylen;
    for (var i = 0; i < ops.length; i++) {
      if (ops[i].key == Operation.retainKey) {
        mylen = (mylen ?? 0) + (ops[i].length ?? 0);
      }
    }

    final base = Delta.from(doc.toDelta());
    final inverseDelta = delta.invert(base);
    dest.add(inverseDelta);
    lastRecorded = 0;
    ignoreChange = true;
    doc.compose(delta, ChangeSource.LOCAL);
    ignoreChange = false;
    return HistoryChanged(true, mylen);
  }

```

**Comment by NehaKushwah993** [comment] 2024-01-17 12:44
Hi, is this resolved?

**Comment by lucasarcouto** [comment] 2024-01-18 20:47
@li3317 could you please revisit this one and maybe reopen it? This is still happening in the current version (9.2.6). 

I really love this package and appreciate all the work that went into it, but feels like a legitimate bug is just being ignored for over 6 months.

**Comment by ellet0** [comment] 2024-03-24 19:10
> @ellet0, could you please take a look?

I might do but expect nothing from me please

Thank you for your understanding
