### ISSUE TITLE
Editor for web app keeps showing "paste" dialog everytime in a read only content page from IOS web browser 

### ISSUE THREAD

**Issue by Salvador-dev** [singerdmx/flutter-quill#1567] opened 2023-12-05 20:33 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

8.6.4

### Steps to reproduce

i'm trying to use the widget in a flutter web app but this issue doesn't have solution since 2022 where another person have the same problem

### Expected results

Don't show the dialog or only one time on the first time in the app.

### Actual results

Showed the dialog every time.

### Code sample

```dart
class ReadingDetailDialog extends StatefulWidget {
  final Reading reading;
  final User user;
  final BaseSubCategory? subCategory;

  const ReadingDetailDialog({
    super.key,
    required this.reading,
    required this.user,
    this.subCategory,
  });

  @override
  State<ReadingDetailDialog> createState() => _ReadingDetailDialogState();
}

class _ReadingDetailDialogState extends State<ReadingDetailDialog>
    with Notificable, Tools, UsesBreakpoints {
  final ReadingBloc _readingBloc;

  _ReadingDetailDialogState()
      : _readingBloc = getIt(),
        super();

  @override
  void initState() {
    _readingBloc.add(RequestOne(widget.reading.id));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return DialogsLayout(
      padding: const EdgeInsets.symmetric(horizontal: 25),
      appBarLeadingWidget: _clientAppBarLeading,
      appBarTitle: _adminAppBarTitle,
      child: BlocBuilder<ReadingBloc, BaseState>(
        bloc: _readingBloc,
        builder: (context, state) {
          if (state is ItemLoaded<DetailedReading>) {
            return _getContent(state.item);
          } else if (state is BaseError) {
            return const TryAgainLaterScreen();
          }
          return LoadingScreen(resource: tr('fields.audio'));
        },
      ),
    );
  }

  Widget get _clientAppBarLeading => widget.user.isClient
      ? CustomDialogDefaults.clientAppBarLeading(
          widget.reading.id,
          getIt<ReadingFavoriteCubit>(),
        )
      : Container();

  Widget? get _adminAppBarTitle =>
      widget.user.isAdmin && widget.subCategory != null
          ? CustomDialogDefaults.adminAppBarTitle(widget.subCategory!)
          : Container();

  Widget _getContent(DetailedReading reading) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.start,
      mainAxisSize: MainAxisSize.max,
      children: [
        Flexible(
          child: NFMarquee(
            text: reading.name,
            style: GoogleFonts.italianno(
              color: Colors.black,
              fontSize: 45,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
        Flexible(
          child: RichText(
            text: TextSpan(
              children: [
                TextSpan(
                  text: "por",
                  style: GoogleFonts.italianno(
                    color: Colors.black87,
                    fontSize: 30,
                    fontWeight: FontWeight.normal,
                  ),
                ),
                TextSpan(
                  text: " some name",
                  style: GoogleFonts.italianno(
                    color: Colors.black,
                    fontSize: 30,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ],
            ),
            textAlign: TextAlign.right,
          ),
        ),
        const Divider(height: 20),
        QuillProvider(
          configurations: QuillConfigurations(
            controller: _getController(reading),
          ),
          child: Expanded(
            flex: 10,
            // child: QuillEditor.basic(
            //   configurations: const QuillEditorConfigurations(
            //     readOnly: true,
            //     enableInteractiveSelection: false,
            //   ),
            // ),
            child: QuillEditor.basic(
              configurations: const QuillEditorConfigurations(
                readOnly: true,
                showCursor: false,
                enableSelectionToolbar: false,
                scrollable: true,
                autoFocus: false,
              ),
            ),
          ),
        ),
      ],
    );
  }

  QuillController _getController(DetailedReading reading) {
    final controller = QuillController.basic();
    if (reading.format == "html") {
      controller.document = Document.fromDelta(
        HtmlToDeltaConverter.htmlToDelta(
          reading.text!,
        ),
      );
    } else {
      controller.document = Document.fromJson(
        jsonDecode(
          reading.text!,
        ),
      );
    }

    return controller;
  }
}
```

### Screenshots or Video

<details>
<summary
![WhatsApp Image 2023-12-05 at 4 31 32 PM](https://github.com/singerdmx/flutter-quill/assets/83884209/320c0579-140a-43dd-a7c5-56635107b69f)
![WhatsApp Image 2023-12-05 at 4 31 32 PM (1)](https://github.com/singerdmx/flutter-quill/assets/83884209/0ab8dff7-30c4-4ea8-aa33-761370ff77a6)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by singerdmx** [comment] 2023-12-05 20:33
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by parseramuser4** [comment] 2023-12-06 06:17
Hello. This issue has been happening to me for a few days, and I've tried every method to solve it without success. In the simplest use case, using this editor on the web on iOS, this problem exists. As far as I understand, this occurs when tapping on any element of the editor, and typing also prevents the user from continuing to type. I created a blank page with the editor, and no specific settings have been applied. Please investigate and resolve this issue as soon as possible.

![Simulator Screen Shot - iPhone 13 Pro Max - 2023-12-06 at 09 30 32](https://github.com/singerdmx/flutter-quill/assets/70637795/2bc1c042-fd02-4914-b315-a3068c5650f0)


`import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart';

class Test extends StatefulWidget {
  const Test({super.key});

  @override
  State<Test> createState() => _TestState();
}

class _TestState extends State<Test> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: QuillProvider(
      configurations: QuillConfigurations(
        controller: QuillController.basic(),
        sharedConfigurations: const QuillSharedConfigurations(),
      ),
      child: Column(
        children: [
          const QuillToolbar(),
          Expanded(
            child: QuillEditor.basic(
              configurations: QuillEditorConfigurations(
                readOnly: false,
              ),
            ),
          )
        ],
      ),
    ));
  }
}
`

**Comment by Salvador-dev** [comment] 2023-12-06 10:43
Yeah this is the same problem we have, even on the latest versions os IOS

![WhatsApp Image 2023-12-05 at 4 31 32 PM (1)](https://github.com/singerdmx/flutter-quill/assets/83884209/6b1a2aee-164a-4c57-8127-cb673615940b)
![WhatsApp Image 2023-12-05 at 4 31 32 PM](https://github.com/singerdmx/flutter-quill/assets/83884209/cbfc48de-55e3-4dcf-98e1-36470d8f9d2a)

**Comment by cgzdevelopments** [comment] 2023-12-06 12:09
@Salvador-dev  We have the same problem with our app. The Paste dialog does not allow the user to continue using the app and the editor is in "readonly" mode.

**Comment by Joharte** [comment] 2023-12-06 12:31
Good day, the same thing happens to me in my web application.  In the case of android I see a dialog that wants to see the text and images that have been copied to the clipboard and in the case of IOS as soon as I touch the screen the paste button appears even when I am in read only (bad experience for the user who is only going to read and says Paste) I ask you please can help me with this

**Comment by freshtechtips** [comment] 2023-12-08 06:46
Hi, can you tell me how to encounter the issue in detail? I can't get it
Besides the toolbar in read-only mode usually hidden
![image](https://github.com/singerdmx/flutter-quill/assets/73608287/b42387ab-0cb8-4c9e-a708-bfcde4f3d4de)

**Comment by Salvador-dev** [comment] 2023-12-08 13:03
> Hi, can you tell me how to encounter the issue in detail? I can't get it Besides the toolbar in read-only mode usually hidden ![image](https://private-user-images.githubusercontent.com/73608287/288987266-b42387ab-0cb8-4c9e-a708-bfcde4f3d4de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNDA2ODQsIm5iZiI6MTcwMjA0MDM4NCwicGF0aCI6Ii83MzYwODI4Ny8yODg5ODcyNjYtYjQyMzg3YWItMGNiOC00YzllLWE3MDgtYmZjZGU0ZjNkNGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDEyNTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYmVlMzY4MjE5N2NhYTZmOTVhMWE2NTRjNjc5OWUyNWE5MDUwZTYxMDFiNTQ0OWYyYmY1YzEwMGFhYzQyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hIvcCIX2PjcV-3SAckzlNXmZYuxiQHhdvpUHxVRLy5Q)

The issue we have is not in IOS app, is for WEB app but when we try to use it through the iphone web navigator

**Comment by Salvador-dev** [comment] 2023-12-08 13:05
> Hi, can you tell me how to encounter the issue in detail? I can't get it Besides the toolbar in read-only mode usually hidden ![image](https://private-user-images.githubusercontent.com/73608287/288987266-b42387ab-0cb8-4c9e-a708-bfcde4f3d4de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNDA2ODQsIm5iZiI6MTcwMjA0MDM4NCwicGF0aCI6Ii83MzYwODI4Ny8yODg5ODcyNjYtYjQyMzg3YWItMGNiOC00YzllLWE3MDgtYmZjZGU0ZjNkNGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDEyNTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYmVlMzY4MjE5N2NhYTZmOTVhMWE2NTRjNjc5OWUyNWE5MDUwZTYxMDFiNTQ0OWYyYmY1YzEwMGFhYzQyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hIvcCIX2PjcV-3SAckzlNXmZYuxiQHhdvpUHxVRLy5Q)

You are using the same versions? (Flutter Quill version : 8.6.4, Flutter version : 3.16.1)

**Comment by cgzdevelopments** [comment] 2023-12-09 09:09
@freshtechtips Hi, thanks for looking at this issue. I've noticed that it doesnt happen on simulator as i've tested on a IOS 15, 16 and 17 simulator and is working fine (no "Paste" dialog shows up). But i also tested on IOS 15, 16 and 17 real devices and "Paste" dialog shows up.

**Comment by freshtechtips** [comment] 2023-12-09 11:03
> @freshtechtips Hi, thanks for looking at this issue. I've noticed that it doesnt happen on simulator as i've tested on a IOS 15, 16 and 17 simulator and is working fine (no "Paste" dialog shows up). But i also tested on IOS 15, 16 and 17 real devices and "Paste" dialog shows up. 

Thanks for the info

That's might be the problem

We are checking if the iOS is a simulator in some places

**Comment by Joharte** [comment] 2023-12-09 12:04
Exactly in the simulator you don't see the "Paste" but on Apple devices it does appear and on Android devices it asks for permission only the first time you enter I was reading the documentation and I saw
  **RawEditorState** extends **EditorState** please review and help me

**Comment by freshtechtips** [comment] 2023-12-09 12:09
> Exactly in the simulator you don't see the "Paste" but on Apple devices it does appear and on Android devices it asks for permission only the first time you enter I was reading the documentation and I saw
>   **RawEditorState** extends **EditorState** please review and help me
> 

On Android, can you tell me which permissions it asks for?

**Comment by Joharte** [comment] 2023-12-09 12:42
Android 
![issue](https://github.com/singerdmx/flutter-quill/assets/116974973/13fa51bd-5e19-493c-9bd3-066b6ac15e93)



real devices read-only mode (in the text viewer) if you do not accept "paste" the data does not appear

![issue ios apenas abro el visor](https://github.com/singerdmx/flutter-quill/assets/116974973/2c0af1b1-160f-4b59-ae31-e640291627c5)

It seems that the editor will store the information on the clipboard, Only if I press the paste button does the text in the viewer appear


Thank you for your prompt response

**Comment by parseramuser4** [comment] 2023-12-14 06:02
@singerdmx @freshtechtips 
Hello. Has any action been taken on this issue? My application has become unusable for iOS users. This problem has been occurring for two weeks, and no action has been taken yet. Please prioritize addressing this issue. Many users are affected by this, but they may not have noticed it yet. Thank you for the time you spend on maintaining this practical extension.

**Comment by freshtechtips** [comment] 2023-12-14 06:52
> @singerdmx @freshtechtips 
> Hello. Has any action been taken on this issue? My application has become unusable for iOS users. This problem has been occurring for two weeks, and no action has been taken yet. Please prioritize addressing this issue. Many users are affected by this, but they may not have noticed it yet. Thank you for the time you spend on maintaining this practical extension.

Hi, I will try to reproduce it again and debug it today

**Comment by freshtechtips** [comment] 2023-12-14 07:28
> @singerdmx @freshtechtips Hello. Has any action been taken on this issue? My application has become unusable for iOS users. This problem has been occurring for two weeks, and no action has been taken yet. Please prioritize addressing this issue. Many users are affected by this, but they may not have noticed it yet. Thank you for the time you spend on maintaining this practical extension.

Still can't reproduce the issue 

![telegram-cloud-photo-size-2-5465388860059013600-y](https://github.com/singerdmx/flutter-quill/assets/73608287/05aeec32-e916-4d6f-9de6-40ca723de46c)
![telegram-cloud-photo-size-2-5465388860059013601-y](https://github.com/singerdmx/flutter-quill/assets/73608287/9af610fe-2d04-4653-b7f3-1c3206a7c7a2)
![telegram-cloud-photo-size-2-5463014713806935419-y](https://github.com/singerdmx/flutter-quill/assets/73608287/3fab6b50-23d2-41c2-8b18-e7a922ab4505)

**Comment by andrewmlevy** [comment] 2023-12-14 07:34
We are experiencing the same issue. Try running the project locally on your mac, once chrome launches open Safari and go to your localhost address with the project and you should be able to reproduce. The issue does not show up in Chrome.

**Comment by andrewmlevy** [comment] 2023-12-18 02:02
@ellet0 or @singerdmx @freshtechtips were you able to reproduce? this is critical for us as well. It's fairly consistent if you run a web build and then point safari to your local server address..  Thanks!

**Comment by ellet0** [comment] 2023-12-18 09:46
> @ellet0 or @singerdmx @freshtechtips were you able to reproduce? this is critical for us as well. It's fairly consistent if you run a web build and then point safari to your local server address..  Thanks!

My apologies but until now I'm unable to reproduce the bug

**Comment by andrewmlevy** [comment] 2023-12-21 20:05
Great news everyone @ellet0 @singerdmx **I was able to recreate the issue**

I ran this gist in Chrome and then loaded the localhost page in Safari (I haven't tested on iOS but I'm sure that will recreate it as well)
https://gist.github.com/andrewmlevy/527950deb95d3aedc0755bbf10f64019

The bug occurs when you hide the editor and then show it again. Click Hide Quill then Show Quill to recreate:
![image](https://github.com/singerdmx/flutter-quill/assets/1203699/a754464b-21af-4216-9191-9110c5a4056a)
![image](https://github.com/singerdmx/flutter-quill/assets/1203699/7b9484bd-6452-4d56-a64b-2eb0f5579504)
![image](https://github.com/singerdmx/flutter-quill/assets/1203699/a2d2aa6a-ad05-43f3-9203-0db18af61448)

The workaround is to use the Offstage widget:
`              Offstage(offstage: !showQuill, child: buildEditor()),
              !showQuill ? Text("No Quill") : Container(),`

However we would still love for the bug to be addressed; this would mean rendering a lot of content to get around it. Thanks!

**Comment by ellet0** [comment] 2023-12-21 21:06
> Great news everyone @ellet0 @singerdmx **I was able to recreate the issue**
> 
> I ran this gist in Chrome and then loaded the localhost page in Safari (I haven't tested on iOS but I'm sure that will recreate it as well) https://gist.github.com/andrewmlevy/527950deb95d3aedc0755bbf10f64019
> 
> The bug occurs when you hide the editor and then show it again. Click Hide Quill then Show Quill to recreate: ![image](https://private-user-images.githubusercontent.com/1203699/292308290-a754464b-21af-4216-9191-9110c5a4056a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTI1ODYsIm5iZiI6MTcwMzE5MjI4NiwicGF0aCI6Ii8xMjAzNjk5LzI5MjMwODI5MC1hNzU0NDY0Yi0yMWFmLTQyMTYtOTE5MS05MTEwYzVhNDA1NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMjA1ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjlkNmM0NjIxMDk1OTM5OTI2N2ZmMDU1NjkyOTUyZTViYjFhOTFjMDgxMWY3ZTg3OTI3MDJjYTM2OGY3NDIzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k8AVotBwD6z1jygPO3mVkaZ01kxY2jhODqCXsUmrD1I) ![image](https://private-user-images.githubusercontent.com/1203699/292308319-7b9484bd-6452-4d56-a64b-2eb0f5579504.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTI1ODYsIm5iZiI6MTcwMzE5MjI4NiwicGF0aCI6Ii8xMjAzNjk5LzI5MjMwODMxOS03Yjk0ODRiZC02NDUyLTRkNTYtYTY0Yi0yZWIwZjU1Nzk1MDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMjA1ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGI3YzIwZGUyNDI0OTYyYjljNWNhNmQ1MGVhNWM5YjZmMzAyYzhjZGY3OTdkYjNkMzEyNWE3NjI4MzI0NjNhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dHqwgU_kIVCm8cC406y2xHEhF9NnYBcCSlrFceNPOEk) ![image](https://private-user-images.githubusercontent.com/1203699/292308340-a2d2aa6a-ad05-43f3-9203-0db18af61448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTI1ODYsIm5iZiI6MTcwMzE5MjI4NiwicGF0aCI6Ii8xMjAzNjk5LzI5MjMwODM0MC1hMmQyYWE2YS1hZDA1LTQzZjMtOTIwMy0wZGIxOGFmNjE0NDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMjA1ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWMzMWMyOGY1ZTIzY2ZjM2IzNGEwMmIyZjdjNWMwOTBlNWM0NTQ0M2VmNTZhMTgxZGJkMDA3NzFhMDcxNTU2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3gpYl3YG_S-DCULgEBVkSPOruDpqkkSQPL6ljrCDFBQ)
> 
> The workaround is to use the Offstage widget: ` Offstage(offstage: !showQuill, child: buildEditor()), !showQuill ? Text("No Quill") : Container(),`
> 
> However we would still love for the bug to be addressed; this would mean rendering a lot of content to get around it. Thanks!

My apologies, does the bug happened on all platforms or just iOS on web browser?

**Comment by andrewmlevy** [comment] 2023-12-22 19:10
>> My apologies, does the bug happened on all platforms or just iOS on web browser?

Correct. I have tested on Android and MacOS, the issue is not there. It is just iOS and web browser (safari).

**Comment by ellet0** [comment] 2023-12-28 15:20
Can't test iOS apps on real iPhone for now but I will try

**Comment by mtallenca** [comment] 2023-12-28 19:59
I am seeing this with Safari web on desktop.  Beginning with the latest release of Safari 17.2.1 that comes with MacOS 14.2.1.

**Comment by Mmisiek** [comment] 2023-12-30 22:29
I see this error on Safari on a Mac desktop, too. Safari version 16.5.2 no issues with Chrome on same Mac.

**Comment by Mmisiek** [comment] 2023-12-30 22:50
> Great news everyone @ellet0 @singerdmx **I was able to recreate the issue**
> 
> I ran this gist in Chrome and then loaded the localhost page in Safari (I haven't tested on iOS but I'm sure that will recreate it as well) https://gist.github.com/andrewmlevy/527950deb95d3aedc0755bbf10f64019
> 
> The bug occurs when you hide the editor and then show it again. Click Hide Quill then Show Quill to recreate: ![image](https://private-user-images.githubusercontent.com/1203699/292308290-a754464b-21af-4216-9191-9110c5a4056a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NzYzOTcsIm5iZiI6MTcwMzk3NjA5NywicGF0aCI6Ii8xMjAzNjk5LzI5MjMwODI5MC1hNzU0NDY0Yi0yMWFmLTQyMTYtOTE5MS05MTEwYzVhNDA1NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMjI0MTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjE1MGJlMzY2ZmI4NzRiOWQ0OGY4YjMwNDkwYjUzODNiNDZiZDk2YmMyZWIxZDYxZjEyNzg0NWRiMjNlNWI4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4eHmpOrRMNarU3gh8NLX6MBQurDOb5wgCq4zyncY0XQ) ![image](https://private-user-images.githubusercontent.com/1203699/292308319-7b9484bd-6452-4d56-a64b-2eb0f5579504.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NzYzOTcsIm5iZiI6MTcwMzk3NjA5NywicGF0aCI6Ii8xMjAzNjk5LzI5MjMwODMxOS03Yjk0ODRiZC02NDUyLTRkNTYtYTY0Yi0yZWIwZjU1Nzk1MDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMjI0MTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTlmYmI4ZjBjYTBlMmNiNzQyMzg2ODE1ZDVjYzJiMDdhNDA1ZDk3Zjc0NjYyZTM3YmE2ZjhjY2FlZWQ2OWQ5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YaEUBJAYtX-gnMm_hwF1RU4xq0AfAlJDpD4eZYfuQRI) ![image](https://private-user-images.githubusercontent.com/1203699/292308340-a2d2aa6a-ad05-43f3-9203-0db18af61448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NzYzOTcsIm5iZiI6MTcwMzk3NjA5NywicGF0aCI6Ii8xMjAzNjk5LzI5MjMwODM0MC1hMmQyYWE2YS1hZDA1LTQzZjMtOTIwMy0wZGIxOGFmNjE0NDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMjI0MTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2IzYmM2YzFhMjg5NmI1ZDY0ZGE1N2M0OWU4ZDgzZjQ2NGFhZjM5N2ZjMTk3MjYxZGM5ZmIwN2NjOTUzNmNjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kW6Zn-Of7nqFFC5qupWBZ_GX9V_Zr5EOohMa9cqQqYw)
> 
> The workaround is to use the Offstage widget: ` Offstage(offstage: !showQuill, child: buildEditor()), !showQuill ? Text("No Quill") : Container(),`
> 
> However we would still love for the bug to be addressed; this would mean rendering a lot of content to get around it. Thanks!

I tried this solution but does not work, when Editor is visible it still is stuck in Safari ;(

**Comment by ellet0** [comment] 2024-01-03 15:30
> I see this error on Safari on a Mac desktop, too. Safari version 16.5.2 no issues with Chrome on same Mac. 

I can test it on real iOS now, but I need detailed steps to reproduce the bug because I still can't reproduce
Last time I tried

**Comment by Mmisiek** [comment] 2024-01-04 01:03
> > I see this error on Safari on a Mac desktop, too. Safari version 16.5.2 no issues with Chrome on same Mac.
> 
> I can test it on real iOS now, but I need detailed steps to reproduce the bug because I still can't reproduce Last time I tried

How about this example ? https://gist.github.com/andrewmlevy/527950deb95d3aedc0755bbf10f64019

**Comment by JoepHeijnen** [comment] 2024-01-15 09:57
Is there any progress on this issue? This is quite blocking for our web app.

**Comment by Albert-Jan** [comment] 2024-01-21 09:30
I'm still facing the same issue as above, even on Safari on a MacBook. Would love to help in any way :)

**Comment by andrewmlevy** [comment] 2024-01-21 18:59
Same, this is still causing issues for us

**Comment by Martin-QPT** [comment] 2024-01-23 23:40
Same - luckily my client primarily uses Edge per company policy but any Safari users are seeing this including myself on a physical MacBook.

**Comment by mpalmer-sps** [comment] 2024-01-24 16:43
> I'm able to reproduce the bug, we don't have any platform checking for the browser and we I tried to change the value of isWeb and it didn't help, I tried to disable the context menu of the web and the custom one and it also didn't help, it might be a bug of flutter web itself for supporting different browsers

I don't think its a Flutter Web issue because it *only* happens on screens where the Flutter Quill control is present. Even within the same App. If it was a Flutter web bug then it would show when the Flutter Quill control is not used.

**Comment by ellet0** [comment] 2024-02-17 01:01
Hi, let me know if you still facing the issue, it has been fixed by @mtallenca

If no one is facing the issue then we should get ready to close the issue

**Comment by andrewmlevy** [comment] 2024-02-17 01:08
It looks to be fixed, thanks!!!

**Comment by Mmisiek** [comment] 2024-02-17 05:13
Yea ! fixed, thanks !

**Closed** 2024-04-22 01:02 UTC
Labels: bug
