### ISSUE TITLE
[Web] Exception caught by scheduler library

### ISSUE THREAD

**Issue by Sammy-iiitb** [singerdmx/flutter-quill#153] opened 2021-04-16 11:19 UTC
My issue is about [Web], I am able to setup quill for flutter web, while writing anything in the launched editor in chrome, I am not able to get the changed data in any format which I need to send back to the server either in json or delta. Below is the screenshot of error that is displayed on the console.

![Error1](https://user-images.githubusercontent.com/8670658/114987318-a71d1380-9eb2-11eb-901c-9367e04a4239.png)

Using all the latest versions

**Comment by matuella** [comment] 2021-04-22 21:10
Happening with me as well, tested with version `1.2.0`, failing on Flutter `2.0.3` and `2.0.4`. Possibly a duplicate of #146

**Closed** 2021-04-24 06:54 UTC
