### ISSUE TITLE
Using flutter_quill with integration_test is not possible

### ISSUE THREAD

**Issue by khainke** [singerdmx/flutter-quill#1502] opened 2023-11-03 11:26 UTC
Imo, `integration_test` is a very basic flutter sdk dev dependency. Is there a way to relax the platform dependency of the flutter_quill package, so that flutter_quill at least works together with basic flutter sdk dependencies?

The problem: Every project with an `integration_test` dependency fails with a dependency conflict:

`pubspec.yaml`

```yaml
...

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

...

dependencies:
  flutter_quill: ^8.1.3

...

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

...
```

`flutter pub get` Output:

```
Resolving dependencies... (1.4s)
Note: platform is pinned to version 3.1.0 by flutter_driver from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because every version of integration_test from sdk depends on flutter_driver
  from sdk which depends on platform 3.1.0, every version of integration_test
  from sdk requires platform 3.1.0.
And because flutter_quill >=7.4.12 depends on platform ^3.1.3,
  integration_test from sdk is incompatible with flutter_quill >=7.4.12.
So, because project_name depends on both flutter_quill ^8.1.3 and
  integration_test from sdk, version solving failed.
```

**Comment by freshtechtips** [comment] 2023-11-03 23:00
Thank you for the report. I will checkout soon

**Comment by odiggity25** [comment] 2023-11-04 12:28
I'm getting this as well

```
Note: platform is pinned to version 3.1.0 by flutter_driver from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of integration_test from sdk depends on flutter_driver from sdk which depends on platform 3.1.0, every version of integration_test from sdk requires platform 3.1.0.
And because flutter_quill 8.1.5 depends on platform ^3.1.3 and no versions of flutter_quill match >8.1.5 <9.0.0, integration_test from sdk is incompatible with flutter_quill ^8.1.5.
So, because squabbit depends on both flutter_quill ^8.1.5 and integration_test from sdk, version solving failed.
```

**Comment by freshtechtips** [comment] 2023-11-04 13:38
> I'm getting this as well
> 
> ```
> Note: platform is pinned to version 3.1.0 by flutter_driver from the flutter SDK.
> See https://dart.dev/go/sdk-version-pinning for details.
> 
> 
> Because every version of integration_test from sdk depends on flutter_driver from sdk which depends on platform 3.1.0, every version of integration_test from sdk requires platform 3.1.0.
> And because flutter_quill 8.1.5 depends on platform ^3.1.3 and no versions of flutter_quill match >8.1.5 <9.0.0, integration_test from sdk is incompatible with flutter_quill ^8.1.5.
> So, because squabbit depends on both flutter_quill ^8.1.5 and integration_test from sdk, version solving failed.
> ```

It's easy to fix. We will make the minimum version to 3.1.0 instead of 3.1.3

We will update it soon.

**Comment by freshtechtips** [comment] 2023-11-04 13:48
Please let me know if you still facing the issue in version 8.1.6

if you have any other questions feel free to ask.

**Comment by odiggity25** [comment] 2023-11-04 13:55
Wow, thank you so much for the fast reply! Did you put out a new version already? How long does it normally take for it to become available? I'm getting the error:

```
Because <my-app> depends on flutter_quill ^8.1.6 which doesn't match any versions, version solving failed.
```

**Comment by freshtechtips** [comment] 2023-11-04 14:12
> Wow, thank you so much for the fast reply! Did you put out a new version already? How long does it normally take for it to become available? I'm getting the error:
> 
> ```
> Because <my-app> depends on flutter_quill ^8.1.6 which doesn't match any versions, version solving failed.
> ```

Thanks, but there's no need to thank me, I'm the one who cause this error anyway

About that error, it will get fixed as soon as @singerdmx publish the new version to pub.dev

Meanwhile, use git in pubspec.yaml to get the flutter_quill package

Please take a look at README.MD
in the installation section

**Comment by freshtechtips** [comment] 2023-11-04 14:23
@singerdmx We are not using the `platform` package anywhere in the project?? then why we need it?? is it safier to delete it??

**Comment by singerdmx** [comment] 2023-11-04 14:54
Go ahead delete it

**Comment by freshtechtips** [comment] 2023-11-04 15:44
> Wow, thank you so much for the fast reply! Did you put out a new version already? How long does it normally take for it to become available? I'm getting the error:
> 
> ```
> Because <my-app> depends on flutter_quill ^8.1.6 which doesn't match any versions, version solving failed.
> ```

You can run `flutter pub get` now, the 8.1.6 just got published

Please let me know if the issue is fixed

**Comment by odiggity25** [comment] 2023-11-04 15:47
Awesome, looks like it's working now. Thanks again!

**Comment by freshtechtips** [comment] 2023-11-04 15:48
> Awesome, looks like it's working now. Thanks again!

You are welcome

**Comment by freshtechtips** [comment] 2023-11-04 15:48
> Imo, `integration_test` is a very basic flutter sdk dev dependency. Is there a way to relax the platform dependency of the flutter_quill package, so that flutter_quill at least works together with basic flutter sdk dependencies?
> 
> The problem: Every project with an `integration_test` dependency fails with a dependency conflict:
> 
> `pubspec.yaml`
> 
> ```yaml
> ...
> 
> environment:
>   sdk: ">=3.0.0 <4.0.0"
>   flutter: ">=3.10.0"
> 
> ...
> 
> dependencies:
>   flutter_quill: ^8.1.3
> 
> ...
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> 
>   integration_test:
>     sdk: flutter
> 
> ...
> ```
> 
> `flutter pub get` Output:
> 
> ```
> Resolving dependencies... (1.4s)
> Note: platform is pinned to version 3.1.0 by flutter_driver from the flutter SDK.
> See https://dart.dev/go/sdk-version-pinning for details.
> 
> Because every version of integration_test from sdk depends on flutter_driver
>   from sdk which depends on platform 3.1.0, every version of integration_test
>   from sdk requires platform 3.1.0.
> And because flutter_quill >=7.4.12 depends on platform ^3.1.3,
>   integration_test from sdk is incompatible with flutter_quill >=7.4.12.
> So, because project_name depends on both flutter_quill ^8.1.3 and
>   integration_test from sdk, version solving failed.
> ```

You can try out the new version since the issue is now fixed.

If you have any other questions feel free to ask us

**Closed by freshtechtips** 2023-11-04 15:48 UTC
