### ISSUE TITLE
when will the Flutter-Quill SDK be adapted for the HarmonyOS system?

### ISSUE THREAD

**Issue by wangjinshan** [singerdmx/flutter-quill#2392] opened 2024-11-22 03:54 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

"Hi, when will the Flutter-Quill SDK be adapted for the HarmonyOS system? I need to inform someone about the timeline for its release."

"We urgently need the Flutter-Quill SDK to be adapted for the HarmonyOS system."

Hope this helps!

**Comment by EchoEllet** [comment] 2024-11-22 09:04
Duplicate of #2389

There is no ETA, and we currently don't have a plan for it. Supporting desktop, mobile, and web platforms is already expensive as it's, I prefer to provide better support for current platforms and enhance functionality than adding support for a new platform.

The `TargetPlatform` is part of the Flutter SDK. This is a package target of the Flutter SDK. How can we support HarmonyOS? We can't change the target SDK to a modified version to support a new target platform. Providing another version of `flutter_quill` is also not something we plan on.

Can you give me example packages that support it?

**Comment by wangjinshan** [comment] 2024-11-23 11:41
Subject: Assistance Required for Adapting Flutter Version for HarmonyOS

Dear quill

I hope this email finds you well.

We are currently working on adapting the Flutter version available at [https://gitee.com/harmonycommando_flutter/flutter] for HarmonyOS. However, we have encountered some issues with two specific files: delegate.dart and text_selection.dart.

We are unsure how to adapt these files for the HarmonyOS system. Below are the errors we are facing:

❯ flutter build hap
start hap build...
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:269:13:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
    switch (defaultTargetPlatform) {
            ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:479:13:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
    switch (defaultTargetPlatform) {
            ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:625:13:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
    switch (defaultTargetPlatform) {
            ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:679:15:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
      switch (defaultTargetPlatform) {
              ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:693:15:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
      switch (defaultTargetPlatform) {
              ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:803:17:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
        switch (defaultTargetPlatform) {
                ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:843:15:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
      switch (defaultTargetPlatform) {
              ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/text/text_selection.dart:91
1:13: Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
    switch (defaultTargetPlatform) {
            ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/text/text_selection.dart:10
68:15: Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
      switch (defaultTargetPlatform) {
              ^
Target kernel_snapshot failed: Exception
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:279:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#7      flutterAssemble (package:flutter_tools/src/ohos/hvigor.dart:306:32)
<asynchronous suspension>
#8      OhosHvigorBuilder.flutterBuildPre (package:flutter_tools/src/ohos/hvigor.dart:543:27)
<asynchronous suspension>
#9      OhosHvigorBuilder.buildApplicationPipeLine (package:flutter_tools/src/ohos/hvigor.dart:681:5)
<asynchronous suspension>
#10     OhosHvigorBuilder.buildHap (package:flutter_tools/src/ohos/hvigor.dart:479:5)
<asynchronous suspension>
#11     BuildHapCommand.runCommand (package:flutter_tools/src/commands/build_hap.dart:80:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Error: Failed to compile application for the Ohos.
Running Hvigor task assembleHap...                                     ⣤%                                           


Could you please provide guidance or examples on how to properly adapt these files for HarmonyOS?

Thank you for your assistance.

Best regards,

**Comment by wangjinshan** [comment] 2024-11-23 11:42
@EchoEllet

**Comment by EchoEllet** [comment] 2024-11-23 11:51
> * switch (defaultTargetPlatform)

I don't know anything about **HarmonyOS** though it probably has a similar behavior to **Android**, a workaround:

```dart
switch (defaultTargetPlatform) {
  case TargetPlatform.android:
  case TargetPlatform.ohos:
  // Assuming HarmonyOS has the same behavior as Android...
  break;
}
```

The project uses plugins and dependencies that don't support HarmonyOS yet, so it will probably have broken behavior and buggy.

**Comment by EchoEllet** [comment] 2024-11-23 11:54
> We are currently working on adapting the Flutter version available at [https://gitee.com/harmonycommando_flutter/flutter] for HarmonyOS. However, we have encountered some issues with two specific files: delegate.dart and text_selection.dart.

This seems to be the same issue as [#2389](https://github.com/singerdmx/flutter-quill/issues/2389#issuecomment-2490633716), closing as duplicate. Continue the discussion in there.

**Closed by EchoEllet** 2024-11-23 11:54 UTC
Labels: question
