### ISSUE TITLE
[All] Code blocks and lists continue previous, un-connected lists.

### ISSUE THREAD

**Issue by Blquinn** [singerdmx/flutter-quill#993] opened 2022-11-02 01:58 UTC
In the attached image you can see that the number of the first line in the code block is 6. It should be 1.

It seems to back track to the last ordered list and act as a continuation of that list.

If lists are separated by any other nodes (other than sub-lists) it should start at 1 again.

![image](https://user-images.githubusercontent.com/6005812/199376419-5c237f4c-d338-41e4-bd3d-40ffdda7a0a9.png)

**Comment by singerdmx** [comment] 2022-11-02 02:00
@kulture-rob-snider is the issue introduced by your change?

**Comment by kulture-rob-snider** [comment] 2022-11-04 15:32
i'm not sure if it was an existing issue from before. @Blquinn can you downgrade and see if it is still an issue?

**Comment by Blquinn** [comment] 2022-11-04 15:34
@kulture-rob-snider Downgrade to what version? What change are we referring to?

**Comment by kulture-rob-snider** [comment] 2022-11-04 15:37
@Blquinn version 6.1.0 please

**Comment by Blquinn** [comment] 2022-11-04 15:45
It works as expected on 6.1.0. It would appear the bug was introduced after.

**Comment by kulture-rob-snider** [comment] 2022-11-04 15:50
ok thanks, i'll look into it. the issue i fixed was numbering always reverting to 2:
1. one
2. two
    a. A
    b. B
2. three
2. four

so for the time being, decide which bug is less impactful to your use case

**Comment by singerdmx** [comment] 2022-11-04 16:03
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/122956/200021826-5b99699b-ca6b-443f-93fb-1d3d86bd09dc.png">

I think he has a change that he needs.
I will wait a couple of days and if this issue cannot be fixed I will revert the change by @kulture-rob-snider and publish a new version.
@kulture-rob-snider can submit a new PR together with the reverted change and the fix.

**Comment by singerdmx** [comment] 2022-11-06 02:46
I reverted "fix order list numbering (#988)" in version 6.1.3

**Comment by li3317** [comment] 2022-12-24 06:44
@kulture-rob-snider Hi any update?

**Comment by Blquinn** [comment] 2023-03-31 20:40
I believe this is now broken in a different way.

![image](https://user-images.githubusercontent.com/6005812/229225349-f109170e-cf38-4157-ac54-63c2e4e9a21e.png)

**Comment by freshtechtips** [comment] 2023-10-25 20:58
The issue is still there

![telegram-cloud-photo-size-2-5319232617624752598-y](https://github.com/singerdmx/flutter-quill/assets/73608287/1f45761d-b218-43a7-80a5-b75ec2fee0e6)

**Comment by CatHood0** [comment] 2024-09-22 08:04
I will close this since was fixed at the current version of the package.

**Closed by CatHood0** 2024-09-22 08:04 UTC
Labels: bug
