### ISSUE TITLE
Exception and malfunction when trying to insert an image

### ISSUE THREAD

**Issue by graemep-nz** [singerdmx/flutter-quill#1605] opened 2023-12-16 06:41 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.0.2

### Other Flutter Quill packages versions

<details><summary>Click To Expand</summary>

```
flutter pub deps -- --style=compact
Dart SDK 3.2.3
Flutter SDK 3.16.4
example 1.0.0+1

dependencies:
- bloc 8.1.2 [meta]
- cached_network_image 3.3.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cross_file 0.3.3+8 [meta web]
- cupertino_icons 1.0.6
- desktop_drop 0.4.4 [flutter flutter_web_plugins cross_file]
- equatable 2.0.5 [collection meta]
- file_picker 6.1.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_bloc 8.1.3 [bloc flutter provider]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_quill 9.0.2 [flutter flutter_localizations intl dart_quill_delta collection quiver equatable meta flutter_colorpicker markdown html2md charcode url_launcher flutter_keyboard_visibility device_info_plus super_clipboard]
- flutter_quill_extensions 9.0.2 [flutter http path meta universal_html cross_file flutter_quill photo_view video_player youtube_player_flutter url_launcher super_clipboard gal gal_linux image_picker]
- flutter_quill_test 9.0.2 [flutter flutter_quill flutter_test]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- hydrated_bloc 9.1.3 [bloc hive meta synchronized]
- image_cropper 5.0.1 [flutter image_cropper_platform_interface image_cropper_for_web]
- json_annotation 4.8.1 [meta]
- path 1.8.3
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- quill_html_converter 9.0.2 [flutter vsc_quill_delta_to_html html2md markdown charcode collection dart_quill_delta]
- share_plus 7.2.1 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- super_clipboard 0.7.3 [flutter collection meta super_native_extensions]

dev dependencies:
- build_runner 2.4.7 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_gen_runner 5.3.2 [flutter_gen_core build collection crypto glob path]
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- freezed 2.4.6 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]

dependency overrides:
- flutter_quill 9.0.2 [flutter flutter_localizations intl dart_quill_delta collection quiver equatable meta flutter_colorpicker markdown html2md charcode url_launcher flutter_keyboard_visibility device_info_plus super_clipboard]
- flutter_quill_extensions 9.0.2 [flutter http path meta universal_html cross_file flutter_quill photo_view video_player youtube_player_flutter url_launcher super_clipboard gal gal_linux image_picker]
- flutter_quill_test 9.0.2 [flutter flutter_quill flutter_test]
- quill_html_converter 9.0.2 [flutter vsc_quill_delta_to_html html2md markdown charcode collection dart_quill_delta]

transitive dependencies:
- _fe_analyzer_shared 64.0.0 [meta]
- analyzer 6.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.2.11 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.8.1 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 3.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- charcode 1.3.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- code_builder 4.9.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- color 3.0.0
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dart_quill_delta 0.0.1 [collection diff_match_patch quiver]
- dart_style 2.3.4 [analyzer args collection path pub_semver source_span]
- dartx 1.2.0 [characters collection crypto meta path time]
- device_info_plus 9.1.1 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- fixnum 1.1.0
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_colorpicker 1.0.3 [flutter]
- flutter_gen_core 5.3.2 [path yaml mime xml dartx color collection json_annotation glob dart_style args pub_semver]
- flutter_inappwebview 5.8.0 [flutter]
- flutter_keyboard_visibility 5.4.1 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- frontend_server_client 3.2.0 [async path]
- gal 2.2.0 [flutter]
- gal_linux 0.0.1 [flutter gal path]
- glob 2.1.2 [async collection file path string_scanner]
- graphs 2.3.1 [collection]
- hive 2.2.3 [meta crypto]
- html 0.15.4 [csslib source_span]
- html2md 1.3.1 [html collection]
- html_unescape 2.0.0
- http 1.1.2 [async http_parser meta web]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_cropper_for_web 3.0.0 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 5.0.0 [flutter plugin_platform_interface http]
- image_picker 1.0.5 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- image_picker_android 0.8.9+1 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.1 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.1 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- intl 0.18.1 [clock meta path]
- io 1.0.4 [meta path string_scanner]
- irondash_engine_context 0.4.0 [flutter plugin_platform_interface]
- irondash_message_channel 0.3.1 [flutter ffi]
- js 0.6.7 [meta]
- lints 3.0.0
- logging 1.2.0
- markdown 7.1.1 [args meta]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- mime 1.0.4
- nested 1.0.0 [flutter]
- octo_image 2.0.0 [flutter]
- package_config 2.1.0 [path]
- path_provider_android 2.2.1 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 6.0.2 [meta]
- photo_view 0.14.0 [flutter]
- pixel_snap 0.1.4 [flutter]
- platform 3.1.3
- plugin_platform_interface 2.1.7 [meta]
- pool 1.5.1 [async stack_trace]
- provider 6.1.1 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.1 [matcher]
- rxdart 0.27.7
- share_plus_platform_interface 3.3.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.0 [flutter sqflite_common path]
- video_player_android 2.4.10 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.3 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.1 [flutter plugin_platform_interface]
- video_player_web 2.1.2 [flutter flutter_web_plugins video_player_platform_interface]
- vsc_quill_delta_to_html 1.0.3 [html_unescape collection meta]
- watcher 1.1.0 [async path]
- web 0.3.0
- web_socket_channel 2.4.0 [async crypto stream_channel]
- win32 5.1.1 [ffi]
- win32_registry 1.1.2 [ffi win32]
- xdg_directories 1.0.3 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
- youtube_player_flutter 8.1.2 [flutter flutter_inappwebview]

```

</details>

### Steps to reproduce

Using the example app in the example folder
1. starting with an empty window (start from scratch)
2. click the "image" icon on the toolbar and select an image
3. the editor asks me to crop the image - even though it's only a 44kb png image
4. when click the "crop" button, android studio reports an exception and the edit window shows this
![image](https://github.com/singerdmx/flutter-quill/assets/39331416/10d87aa7-e53c-4523-b105-cce5b3fa866f)
- a red box with the words unsupported operation _Namespace

<details><summary>Click To Expand</summary>

```
======== Exception caught by image resource service ================================================
The following UnsupportedError was thrown resolving an image codec:
Unsupported operation: _Namespace

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 210:5                   get _namespacePointer
dart-sdk/lib/io/file_impl.dart 254:48                                             _namespacePointer
dart-sdk/lib/io/file_impl.dart 257:15                                             _dispatchWithNamespace
dart-sdk/lib/io/file_impl.dart 388:58                                             length
packages/flutter/src/painting/image_provider.dart 1481:42                         _loadAsync
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/painting/image_provider.dart 1472:30                         [_loadAsync]
packages/flutter/src/painting/image_provider.dart 1463:14                         loadImage
packages/flutter/src/painting/image_provider.dart 520:39                          <fn>
packages/flutter/src/painting/image_cache.dart 377:22                             putIfAbsent
packages/flutter/src/painting/image_provider.dart 517:81                          resolveStreamForKey
packages/flutter/src/widgets/scroll_aware_image_provider.dart 104:5               resolveStreamForKey
packages/flutter/src/painting/image_provider.dart 366:9                           <fn>
packages/flutter/src/painting/image_provider.dart 479:9                           <fn>
packages/flutter/src/foundation/synchronous_future.dart 43:39                     then
packages/flutter/src/painting/image_provider.dart 476:8                           [_createErrorHandlerAndKey]
packages/flutter/src/painting/image_provider.dart 363:5                           resolve
packages/flutter/src/widgets/image.dart 1110:15                                   [_resolveImage]
packages/flutter/src/widgets/image.dart 1060:5                                    didChangeDependencies
packages/flutter/src/widgets/framework.dart 5620:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 5447:5                                mount
packages/flutter/src/widgets/framework.dart 4326:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3837:18                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5453:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 5447:5                                mount
packages/flutter/src/widgets/framework.dart 4326:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3837:18                               updateChild
packages/flutter/src/widgets/framework.dart 6736:14                               mount
packages/flutter/src/widgets/framework.dart 4326:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3837:18                               updateChild
packages/flutter/src/widgets/framework.dart 6736:14                               mount
packages/flutter/src/widgets/framework.dart 4326:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3837:18                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5453:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 5625:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 5447:5                                mount
packages/flutter/src/widgets/framework.dart 4326:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3837:18                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5453:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 5447:5                                mount
packages/flutter/src/widgets/framework.dart 4326:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3837:18                               updateChild
packages/flutter/src/widgets/framework.dart 6736:14                               mount
packages/flutter/src/widgets/framework.dart 4326:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3837:18                               updateChild
packages/flutter/src/widgets/framework.dart 6736:14                               mount
packages/flutter/src/widgets/framework.dart 4326:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3837:18                               updateChild
packages/flutter/src/widgets/framework.dart 6736:14                               mount
packages/flutter/src/widgets/framework.dart 4326:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3837:18                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5453:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 5447:5                                mount
packages/flutter/src/widgets/framework.dart 4326:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 6871:36                               inflateWidget
packages/flutter/src/widgets/framework.dart 3837:18                               updateChild
packages/flutter/src/widgets/framework.dart 4024:32                               updateChildren
packages/flutter/src/widgets/framework.dart 6896:17                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5657:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter_quill/src/widgets/quill/text_line.dart 1403:22                   [_updateChild]
packages/flutter_quill/src/widgets/quill/text_line.dart 1353:5                    update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5800:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 3964:32                               updateChildren
packages/flutter/src/widgets/framework.dart 6896:17                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5657:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5800:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5800:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5657:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5800:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5800:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5657:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5547:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5657:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5547:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5547:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5800:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5657:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5800:5                                update
packages/flutter/src/widgets/inherited_notifier.dart 105:11                       update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5657:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5800:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5657:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5800:5                                update
packages/flutter/src/widgets/inherited_notifier.dart 105:11                       update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5657:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5657:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 5800:5                                update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 6743:14                               update
packages/flutter/src/widgets/framework.dart 3815:14                               updateChild
packages/flutter/src/widgets/framework.dart 5496:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5634:11                               performRebuild
packages/flutter/src/widgets/framework.dart 5187:7                                rebuild
packages/flutter/src/widgets/framework.dart 2895:18                               buildScope
packages/flutter/src/widgets/binding.dart 984:9                                   drawFrame
packages/flutter/src/rendering/binding.dart 457:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1325:7                                [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1255:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1113:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1274:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 248:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 186:36                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Path: blob:http://localhost:61133/f0e19531-eeab-42b9-b9f7-cf807c13e75c
====================================================================================================

```

</details>

### Expected results

The image should be loaded and be visible in the edit window.

### Actual results

get a small red rectangle with an error message "unsupported operation"

### Code sample

Using the example from the github repo with no changes

**Comment by singerdmx** [comment] 2023-12-16 06:41
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by freshtechtips** [comment] 2023-12-16 20:50
Hi, can you provide info about which platform you are using?? more info because I couldn't reproduce the bug

**Comment by graemep-nz** [comment] 2023-12-16 21:07
ok, sorry  - it's the web platform  -  google chrome latest release on Win 11 latest release using Android Studio.  I'll make a video - attached is the image I tried to load.
![err1](https://github.com/singerdmx/flutter-quill/assets/39331416/cf74cbb9-2ac7-44cf-833c-6ed8621c26cf)

**Comment by freshtechtips** [comment] 2023-12-16 21:22
Thanks! There is no need to be sorry. but I still need more info

All I know is you are using the `example` and in there you are inserting an image using the toolbar button

**Comment by graemep-nz** [comment] 2023-12-16 21:34
Yes, the example app from the repo - I had to do pub get and pub upgrade to get it to build I thing.  I got the code from the github repo, not pub dev  - I guess I should have used pub dev.  Hopefully attached is a video.

https://github.com/singerdmx/flutter-quill/assets/39331416/3a0178de-cc0c-43ae-bb6b-e525aa6978bf

**Comment by freshtechtips** [comment] 2023-12-16 21:41
> Yes, the example app from the repo - I had to do pub get and pub upgrade to get it to build I think. I got the code from the github repo, not pub dev - I guess I should have used pub dev. Hopefully attached is a video.
> 
>  flutter-quill-bug-report1.mp4

Can you send me the log?

**Comment by graemep-nz** [comment] 2023-12-16 21:41
where do i get the log from?

**Comment by graemep-nz** [comment] 2023-12-16 21:56
log from devtools
[bug-report2.txt](https://github.com/singerdmx/flutter-quill/files/13694031/bug-report2.txt)

**Comment by freshtechtips** [comment] 2023-12-16 22:11
Thanks! the bug fixed in `9.0.3`

**Comment by freshtechtips** [comment] 2023-12-16 22:14
We are publishing `9.0.3`
can you now try the example and see if it works as expected?

**Comment by graemep-nz** [comment] 2023-12-16 22:32
Yes it works correctly now thanks!
Why does it crop the image - it's only 44 kB.
Also where does it put the image - is it possible to have it embedded in the file as a base64 kind of thing?
Thanks.

**Comment by graemep-nz** [comment] 2023-12-16 22:33
also in the example app "writting" should be "writing"

**Comment by freshtechtips** [comment] 2023-12-16 22:41
> Yes it works correctly now thanks!
> Why does it crop the image - it's only 44 kB.
> Also where does it put the image - is it possible to have it embedded in the file as a base64 kind of thing?
> Thanks.

Cropping images feature only enabled in the example, and it always triggered no matter the size, just an example 


Yes, you can have the image in base 64

By default, it caches the image on mobile, on desktop it added it like ut

You can override all of this

**Comment by graemep-nz** [comment] 2023-12-16 22:46
Great, thanks.

**Comment by freshtechtips** [comment] 2023-12-17 13:04
If you have any questions, feel free to ask.

**Closed by freshtechtips** 2023-12-17 13:04 UTC
Labels: bug

**Comment by Chandu-bs** [comment] 2024-01-09 07:51
I still have this issue with latest version too, can anyone help?

**Comment by graemep-nz** [comment] 2024-01-09 10:38
> I still have this issue with latest version too, can anyone help?

Which version are you using.  9.0.3 ??

**Comment by Chandu-bs** [comment] 2024-01-09 11:07
> > I still have this issue with latest version too, can anyone help?
> 
> Which version are you using. 9.0.3 ??

9.2.2, i have made a issue thread too
