### ISSUE TITLE
flutter_quill/extensions error in flutter 3.24.3

### ISSUE THREAD

**Issue by CherishMvp** [singerdmx/flutter-quill#2257] opened 2024-09-21 02:45 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

when i use "import 'package:flutter_quill/extensions.dart'
    show isAndroid, isDesktop, isIOS, isWeb;" in flutter 3.24.3 ,shows The library 'package:flutter_quill/extensions.dart' doesn't export a member with the shown name 'isIOS'.
Try removing the name from the list of shown members.dart[undefined_shown_name](https://dart.dev/diagnostics/undefined_shown_name)
![image](https://github.com/user-attachments/assets/915e7633-37c8-44c4-bc85-5f19a7029dc3)

**Comment by EchoEllet** [comment] 2024-09-21 10:25
Update both `flutter_quill` and `flutter_quill_extensions` to the latest version. Also, the `extensions.dart` from `flutter_quill` should not be used. It's for internal use only. 

We do plan on adding `internal` to the name to make it more clear.

**Comment by EchoEllet** [comment] 2024-09-21 12:44
Was unable to reproduce this issue even after removing `pubspec overrides.yaml` and upgrading Flutter to 3.24.3 from 3.24.2.

Should be fixed in [10.7.3](https://github.com/singerdmx/flutter-quill/releases/tag/v10.7.3) as the minimum version of `flutter_quill` in `flutter_quill_extensions` has been increased.

Closing the issue. Can you confirm if it's fixed the issue persists?

**Comment by CherishMvp** [comment] 2024-09-25 02:58
thanks for your replay. but it seems like the issue still not fixed in my project. this is my version screenshot
![image](https://github.com/user-attachments/assets/501e5447-951c-4f36-95de-6f7666f2509c)

**Comment by EchoEllet** [comment] 2024-09-25 10:43
- Can you try with [10.7.7](https://pub.dev/packages/flutter_quill/versions/10.7.7) for both `flutter_quill` and `flutter_quill_extensions`? Also run `flutter clean && flutter pub get`
- Can you try to reproduce the issue in a new minimal project or in the example app of `flutter_quill`?
- Does removing `flutter_quill_extensions` fix the issue (which should)
- Can you run `flutter pub deps` and share the output?

**Comment by CherishMvp** [comment] 2024-09-26 01:53
I seem to know the problem because I used an older version of the sample demo but my version of flutter was upgraded. I also used flutter pub cache repair and flutter pub cache clean and now it seems to be working properly. Thank you very much
● flutter doctor && flutter --version
  ○ 
![image](https://github.com/user-attachments/assets/0265e9cb-7a15-473e-a0a4-9eb7b976aad5)

● flutter launch in vscode
before add   flutter_quill: ^10.5.5  and flutter_quill_extensions: ^10.5.5
  ○ 
![image](https://github.com/user-attachments/assets/a93350e8-3624-4438-94a0-370eb38c3649)

  ○

**Comment by EchoEllet** [comment] 2024-09-26 08:55
You're welcome. It seems that we're using some dependencies that require a newer version of Flutter.

**Closed by EchoEllet** 2024-09-26 08:55 UTC
Labels: question
