### ISSUE TITLE
List items cut off before text is added

### ISSUE THREAD

**Issue by jgadsby** [singerdmx/flutter-quill#45] opened 2021-02-27 13:50 UTC
Hi,

I'm enjoying using this library so far - great work. I did spot a small bug when adding new lines. The screenshot sums it up - when adding a new line in a list item, the leading indicators (e.g. 1., 2.) are cut off vertically before text is added. When text is added, they are no longer cut off.

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-27 at 13 48 13](https://user-images.githubusercontent.com/4282877/109389084-b8aa5c00-7902-11eb-94c8-44ab8c91a889.png)

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-27 at 13 49 52](https://user-images.githubusercontent.com/4282877/109389089-bf38d380-7902-11eb-9586-097a94f77769.png)

**Comment by li3317** [comment] 2021-02-27 19:29
Hello, we can't seem to reproduce this issue, are you trying this on an emulator or an actual phone ?

**Comment by jgadsby** [comment] 2021-02-27 20:15
It happens for me on an iPhone 12 Pro Max (device) and emulator. I have adjusted the vertical heights for list styles - do you have any guidance on what the first and second doubles in the height Tuples are for?

**Comment by singerdmx** [comment] 2021-02-27 20:46
![image](https://user-images.githubusercontent.com/122956/109399803-d3c49e00-78f9-11eb-97f2-7a0710b94638.png)


The code should be here. 
Since we are unable to repro your issue, you are welcome to submit a pull request

**Comment by singerdmx** [comment] 2021-02-27 20:47
I guess we can replace paragraph style with something else that fits your need.

**Comment by singerdmx** [comment] 2021-02-27 20:47
As long as we test your change and it does not break other things, we will merge your change

**Comment by jgadsby** [comment] 2021-02-28 12:52
@singerdmx This issue is really easy to reproduce if you simply change the 'paragraph' TextStyle in customStyles like so:

` paragraph: DefaultTextBlockStyle(
                              TextStyle(
                                  fontSize: 18),
                              Tuple2(8, 16),
                              Tuple2(8, 16),
                              BoxDecoration())),`

 Change the paragraph font size and you can see how that change is being applied to the leading text too (e.g. 1., 2., 3,.) but there isn't enough space to render the text without cutting it off. Maybe the leading text style should inherit the list style provided?

**Comment by singerdmx** [comment] 2021-02-28 17:26
OK. If you have a fix in mind, could you submit a pull request, please?

**Comment by singerdmx** [comment] 2021-02-28 17:32
Are you talking about web or mobile?

**Comment by jgadsby** [comment] 2021-02-28 18:56
This is on mobile.

**Comment by jgadsby** [comment] 2021-03-01 11:21
As mentioned above, I don't have the time nor knowledge of the codebase to fix the issue but it's definitely a problem that you'd want to fix - customizing font sizes seems like a pretty essential feature.

**Comment by ArjanAswal** [comment] 2021-03-01 11:32
So basically the issue is that the list prefixes are using paragraph styles instead of list styles?

**Comment by jgadsby** [comment] 2021-03-01 16:28
> So basically the issue is that the list prefixes are using paragraph styles instead of list styles?
> @jgadsby can you confirm that?

I think so. Like I mentioned above, it's easy to reproduce the bug by simply changing the paragraph font size to be larger than the list font size. Have you tried doing that yet to reproduce the bug?

**Comment by singerdmx** [comment] 2021-03-04 07:22
@jgadsby we can create a new style just to assign to leading icon. No need to reuse paragraph or list style

**Comment by jgadsby** [comment] 2021-03-04 16:24
> @jgadsby we can create a new style just to assign to leading icon. No need to reuse paragraph or list style

That would be great! Thank you.

**Comment by singerdmx** [comment] 2021-03-04 16:25
We need someone to submit MR for this.
I am not able to reproduce.

**Comment by ArjanAswal** [comment] 2021-03-15 16:49
> I am not able to reproduce.

Neither am I.
@jgadsby Any updates regarding this?

**Comment by jgadsby** [comment] 2021-03-15 21:37
I was able to fix my issue by changing the following: 

<img width="811" alt="Screen Shot 2021-03-15 at 9 37 29 PM" src="https://user-images.githubusercontent.com/4282877/111224646-a86ad000-85d6-11eb-86d5-0f91c5bdfbb7.png">

<img width="817" alt="Screen Shot 2021-03-15 at 9 37 22 PM" src="https://user-images.githubusercontent.com/4282877/111224675-b3256500-85d6-11eb-815e-c93dd22937d2.png">

**Comment by singerdmx** [comment] 2021-03-15 21:39
submit a pull request. Looks good

**Comment by singerdmx** [comment] 2021-03-15 21:41
```
        paragraph: DefaultTextBlockStyle(
            baseStyle, Tuple2(0.0, 0.0), Tuple2(0.0, 0.0), null),
```

It seems the same. But sure we should have ur change

**Comment by singerdmx** [comment] 2021-04-03 07:55
Submitted https://github.com/singerdmx/flutter-quill/commit/96b5be1518e9ff4ef7b7ae19663eb88e2d22af01

**Closed by singerdmx** 2021-04-03 07:55 UTC
