### ISSUE TITLE
 [Mobile] Cannot use in Flutter latest stable version (2.2.0)

### ISSUE THREAD

**Issue by WingCH** [singerdmx/flutter-quill#225] opened 2021-05-19 01:25 UTC
My issue is about [Mobile].

## Reproduce step:
1. upgrade to latest stable version (2.2.0)
2. flutter pub get
3. flutter run
```
../lib/widgets/raw_editor.dart:97:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.userUpdateTextEditingValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
/usr/local/bin/flutter/packages/flutter/lib/src/services/text_input.dart:822:8: Context: 'TextSelectionDelegate.userUpdateTextEditingValue' is defined here.
  void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
../lib/widgets/raw_editor.dart:1053:8: Error: The method 'RawEditorState.hideToolbar' has fewer positional arguments than those of overridden method 'TextSelectionDelegate.hideToolbar'.
  void hideToolbar() {
       ^
/usr/local/bin/flutter/packages/flutter/lib/src/services/text_input.dart:829:8: Context: This is the overridden method ('hideToolbar').
  void hideToolbar([bool hideHandles = true]);
       ^


FAILURE: Build failed with an exception.

* Where:
Script '/usr/local/bin/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/usr/local/bin/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Exception: Gradle task assembleDebug failed with exit code 1


```

**Comment by subinsv** [comment] 2021-05-19 06:36
I have the same issue after upgrading to flutter 2.2

**Comment by FelixMittermeier** [comment] 2021-05-19 10:11
Seems like @kevinDespoulains (thank you btw ☺️) is already working on a pull request.
In the meantime you can edit your local copy in the pub cache by applying the following changes manually: https://github.com/singerdmx/flutter-quill/pull/226/commits/f01e161a3f7f307378db547c22c16762d57b12fd

**Comment by friebetill** [comment] 2021-05-19 11:34
The PR #226 is merged, now we have to wait for a new release from @singerdmx.

**Comment by jonmountjoy** [comment] 2021-05-19 12:38
When I use the above @friebetill , it compiles just fine for simulator, but any production build for iOS fails with 

        "../../third_party/dart/runtime/vm/compiler/aot/precompiler.cc: 3186: error: unreachable code
            Dart snapshot generator failed with exit code -6"

ie. `flutter build ios` fails.

**Comment by friebetill** [comment] 2021-05-19 16:59
Thanks for the information, I am working on solving the problem.

The editor runs without problems for me on iOS in debug mode. However, the build for iOS is currently failing for me because of [this issue](https://github.com/flutter/flutter/issues/43986). So I can't reproduce the build problem yet.

I saw that there was already a [similar PR](https://github.com/singerdmx/flutter-quill/pull/180/files) and there was this extra line, maybe someone can add this line and see if it fixes the problem.
```dart
    updateEditingValue(value);
```

**Comment by jonmountjoy** [comment] 2021-05-19 18:29
I did try [find this](https://groups.google.com/g/flutter-dev/c/m15DOpB-zBI) @friebetill - but I couldn't find a way to reproduce that approach to debugging the issue.  I wondered if this was not a problem with the Flutter/Dart compilation system, and whether a bug should be filed with them?

**Comment by friebetill** [comment] 2021-05-19 18:41
`gen_snapshot` with `--trace-compiler` sounds interesting, I haven't heard of it yet. I'll read about it and maybe I can find something out. 

I also noticed that my demotivation to create an issue is mainly because creating a minimum reproducible example is a boring task and I've done exactly that for the last two weeks for [this issue](https://github.com/gql-dart/ferry/issues/189).

**Comment by jongkb** [comment] 2021-05-20 16:27
With flutter_quill 1.3.0 and Flutter 2.2.0, building for release fails on Android. No issues with debug builds though.

`flutter build apk --target-platform android-arm64`

```
 Building with sound null safety 

../../third_party/dart/runtime/vm/compiler/aot/precompiler.cc: 3186: error: unreachable code
Dart snapshot generator failed with exit code -1073740791


FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org   
```

**Comment by friebetill** [comment] 2021-05-21 13:07
I created this [issue](https://github.com/flutter/flutter/issues/83094) in the Flutter repo.

**Comment by XOneto9** [comment] 2021-05-22 07:20
@friebetill 
Thanks, that is work for me! great

**Comment by friebetill** [comment] 2021-05-29 14:10
Closed by https://github.com/singerdmx/flutter-quill/pull/239.

**Closed by friebetill** 2021-05-29 14:10 UTC
