### ISSUE TITLE
is support table? and I want transform to table tag display in web.

### ISSUE THREAD

**Issue by SinglTown** [singerdmx/flutter-quill#1388] opened 2023-09-04 05:49 UTC
how to do that?

**Comment by wildsurfer** [comment] 2023-11-17 11:57
+1

**Comment by Gowsalyanatraj** [comment] 2024-01-03 06:16
+1

**Comment by iremceliksena** [comment] 2024-03-19 11:30
Hello,
I also have html containing <table>. I want to reflect the HTML codes as they are and edit them in the editor. How can I do this, or can I do it? Can it only detect parameters such as <p>?

**Comment by singerdmx** [comment] 2024-06-22 05:24
Duplicate of https://github.com/singerdmx/flutter-quill/issues/1735

**Closed by singerdmx** 2024-06-22 05:24 UTC
