### ISSUE TITLE
[BUG BOUNTY] Can't remove style on paragraphs that are separated by a new line

### ISSUE THREAD

**Issue by FelixMittermeier** [singerdmx/flutter-quill#1550] opened 2023-11-22 19:48 UTC
### Flutter Quill version

8.6.1

### Steps to reproduce

The following bug is really annoying for my users. I am willing to pay 50$/€ to the person who fixes this bug in a not hacky and clean way.

Write two paragraphs (separated by a new line), select both of them (or just "select all") and apply formatting like "bold" or "italic". Then you are not able to remove the style for both paragraphs. The only way is to select each paragraph separately and then you can press the "bold" button again

![169970454-68da30d1-d690-44f9-8678-4355897997dd](https://github.com/singerdmx/flutter-quill/assets/33794642/2bbfdde3-1df1-4ed5-a80f-6a6baa7190ed)

### Expected results

The style removal should directly work also across multiple paragraphs 

### Actual results

Nothing happens when two paragraphs are selected and you try to remove an already applied style

**Comment by jpenna** [comment] 2023-11-24 21:27
I can confirm this is happening.

I want to dive deep on the lib. If the bug is still around by the time I can fix it, I will do it on @singerdmx behalf (they get the bounty).

**Comment by mregnauld** [comment] 2023-11-25 16:08
I'm experiencing the same problem (version 8.6.2).
That being said, if you press the _clear style_ button, the style is removed as expected.

**Comment by freshtechtips** [comment] 2023-11-26 01:46
Hi, thank you for the report

I can confirm that the issue has nothing to do with the `QuillToolbar` or any of the buttons because I already tested it with a custom toolbar that was made from scratch and I still can get the issue

The bug in [controller.dart](https://github.com/singerdmx/flutter-quill/blob/master/lib/src/widgets/controller.dart)
In the function  

```dart
void formatText(int index, int len, Attribute? attribute)
```

For now, it's in line 308 but that could be changed at any time.

**Comment by freshtechtips** [comment] 2023-11-26 21:36
I can confirm the bug happened because of the way the library handles the selection in the editor and the controller

When selecting all:
![image](https://github.com/singerdmx/flutter-quill/assets/73608287/2303d910-c81b-4de8-98e4-913d9476775e)

When selecting only one line:
![image](https://github.com/singerdmx/flutter-quill/assets/73608287/0ba4b5d9-c676-4a4b-8d4c-d0cf7afd951e)

As you can see the `isToggled` state differs, because the icon buttons color will be filled if the `isToggled` is true

**Comment by li3317** [comment] 2024-01-06 02:51
Hello, I'm on mobile version trying to repro this issue but i'm not able to repro, could you provide a sample json or exact step on where this is occurring? this is what i'm doing: 
open the editor -> type something on the first line -> hit return to insert a blank line -> hit return again -> type something on the second line -> apply bold style, then after that i'm able to select both lines and press bold again to remove. Under what scenario are the styles not able to be removed ?

**Comment by ellet0** [comment] 2024-01-06 17:33
> Hello, I'm on mobile version trying to repro this issue but i'm not able to repro, could you provide a sample json or exact step on where this is occurring? this is what i'm doing: open the editor -> type something on the first line -> hit return to insert a blank line -> hit return again -> type something on the second line -> apply bold style, then after that i'm able to select both lines and press bold again to remove. Under what scenario are the styles not able to be removed ?

Please take a look at my comment, the problem that the way that selection work is not working like users expected, when you select all and you have in the first line bold text, second line is empty and third also have bold text

then you will see the button selected state is false because the button is not filled

**Comment by li3317** [comment] 2024-01-07 05:07
Here's the result I see on my end, i'm able to apply bold to different lines (either one by one or all at one time), then select part or all of them to remove the style and it'll remove successfully. I am seeing a different issue though, after removing the style I can't apply it back because it thinks it's already toggled.

https://github.com/singerdmx/flutter-quill/assets/46685982/ab55c43b-7078-4161-9a4d-6f7cbb580dca


https://github.com/singerdmx/flutter-quill/assets/46685982/d39c05c7-aa69-42d1-a74d-3233ebcbe02c

**Comment by FelixMittermeier** [comment] 2024-01-07 08:18
I think you have to add an empty line between the text, then you get the described behavior.

**Comment by li3317** [comment] 2024-01-07 20:14
Like this? 
<img src="https://github.com/singerdmx/flutter-quill/assets/46685982/abfe78d6-1423-4d67-96d6-e1383fcb1cf4" width=50% height=50%>

and then after clicking bold again:
<img src="https://github.com/singerdmx/flutter-quill/assets/46685982/db6b98f0-e2e7-4f18-a5ba-3acb1574c850" width=50% height=50%>

**Comment by singerdmx** [comment] 2024-01-07 20:27
@li3317 so you cannot repro it?

**Comment by FelixMittermeier** [comment] 2024-01-07 20:39
I just tested on the latest version and can still reproduce this issue as described 👀

**Comment by ellet0** [comment] 2024-01-07 21:19
> I just tested on the latest version and can still reproduce this issue as described 👀

Me too

**Comment by li3317** [comment] 2024-01-08 02:55
@singerdmx I'm not able to. Maybe it's different platform.

**Comment by singerdmx** [comment] 2024-01-08 19:56
I think @li3317 is on mobile and she cannot repro it

**Comment by Wrth1** [comment] 2024-03-22 22:43
This bug is so infuriating I decided to spend 5 hours to fix it
The bug is at lib\src\models\documents\nodes\line.dart at line 364-367, it compares `style.attributes[attr.key] != attr.value` when it should actually compare `style.attributes[attr.key]?.value != attr.value`, I guess the reason some people can't repro it is because in some version of dart `anything == (bool)true` while in some version only `(bool)true == (bool)true`

Simply change lib\src\models\documents\nodes\line.dart at line 364-367 to the following
```dart
        if (!style.containsKey(attr.key) ||
            (style.attributes[attr.key]?.value != attr.value)) {
          excluded.add(attr);
        }
```
Some other related issue can be fixed by setting keepStyleOnNewLine to false, see #1775 

I've also created a PR request, #1782

**Comment by Wrth1** [comment] 2024-03-22 22:57
I forgot one thing, we also need to merge the `result` with `rest`, change the line 391- 394 to this
```dart
if (remaining > 0 && nextLine != null) {
      final rest = nextLine!.collectStyle(0, remaining);
      result = result.mergeAll(rest);
      handle(rest);
    }
```

**Closed** 2024-03-24 23:01 UTC
Labels: bug

**Comment by LucasFoulonMongai** [comment] 2024-03-25 08:01
> This bug is so infuriating I decided to spend 5 hours to fix it The bug is at lib\src\models\documents\nodes\line.dart at line 364-367, it compares `style.attributes[attr.key] != attr.value` when it should actually compare `style.attributes[attr.key]?.value != attr.value`, I guess the reason some people can't repro it is because in some version of dart `anything == (bool)true` while in some version only `(bool)true == (bool)true`
> 
> Simply change lib\src\models\documents\nodes\line.dart at line 364-367 to the following
> 
> ```dart
>         if (!style.containsKey(attr.key) ||
>             (style.attributes[attr.key]?.value != attr.value)) {
>           excluded.add(attr);
>         }
> ```
> 
> Some other related issue can be fixed by setting keepStyleOnNewLine to false, see #1775
> 
> I've also created a PR request, #1782


Thanks a lot for fixing the issue !
