### ISSUE TITLE
Add Support for adding custom attributes.

### ISSUE THREAD

**Issue by ritheshSalyan** [singerdmx/flutter-quill#29] opened 2021-02-18 15:15 UTC
Can we add Custom Attributes without editing the source? custom Attribute does not necessarily mean that it is a styling attribute. it can be a non-styling attribute as well.

**Comment by singerdmx** [comment] 2021-02-18 15:26
And just ignore the custom attribute if we don't know how to render it?

**Comment by ritheshSalyan** [comment] 2021-02-18 17:32
I found  `AttributeScope.IGNORE`  scope which throws error on using like this.

```dart

class CustomAttribute extends Attribute<String> {
  CustomAttribute(String value)
      : super("my_attribute", AttributeScope.IGNORE, value);
}

```
because of following function in `Attribute<T>` class 
```dart
  static Attribute fromKeyValue(String key, dynamic value) {
    if (!_registry.containsKey(key)) {
      throw ArgumentError.value(key, 'key "$key" not found.');
    }
    Attribute origin = _registry[key];
    Attribute attribute = clone(origin, value);
    return attribute;
  }
```

**Comment by singerdmx** [comment] 2021-02-18 17:34
The problem is: even if we can ignore custom attribute, we won't be able to retain it after editting

**Comment by singerdmx** [comment] 2021-02-18 17:37
```
  static Style fromJson(Map<String, dynamic> attributes) {
    if (attributes == null) {
      return Style();
    }

    Map<String, Attribute> result = attributes.map((String key, dynamic value) {
      Attribute attr = Attribute.fromKeyValue(key, value);
      return MapEntry<String, Attribute>(key, attr);
    });
    return Style.attr(result);
  }
```

Maybe you can try returning `Style()` here and just return null in `fromKeyValue`

Let me know if it works. If true, you can submit a pull request

**Comment by ritheshSalyan** [comment] 2021-02-18 17:38
ok.

**Comment by singerdmx** [comment] 2021-02-18 17:39
One thing I am unsure is editting. Would we lost those attributes after edtting. You may want to check that.

**Comment by ritheshSalyan** [comment] 2021-02-18 17:40
ok. ill take care of it.

**Comment by singerdmx** [comment] 2021-02-22 22:47
@ritheshSalyan  submitted https://github.com/singerdmx/flutter-quill/commit/0e7a91eb10990f23ab6f1826d7e5b0a1da691485

**Comment by HeebeLee** [comment] 2021-03-05 03:33
I also need this function. I want to have my own format and be able to render its content freely, such as @ effect.

Exposure rendering methods are recommended.

@singerdmx

**Comment by singerdmx** [comment] 2021-03-05 03:35
@HeebeLee you can reference https://github.com/singerdmx/flutter-quill/pull/31 and submit a pull request

**Comment by singerdmx** [comment] 2021-04-03 07:55
Closing since we don't need it

**Closed by singerdmx** 2021-04-03 07:55 UTC

**Comment by krishnaprasadgandrath-nooor** [comment] 2023-04-18 05:16
How Can i Add custom attribute without changing the source? I need to add Shadow to editing Text and we can do it with TextStyle(shadows:['ShadowStyle']); But i don't  want to change the source of quill

**Comment by krishnaprasadgandrath-nooor** [comment] 2023-04-18 05:16
How Can i Add custom attribute without changing the source? I need to add Shadow to editing Text and we can do it with TextStyle(shadows:['ShadowStyle']); But i don't  want to change the source of quill

**Comment by NOVACOAX** [comment] 2024-07-20 17:55
> How Can i Add custom attribute without changing the source? I need to add Shadow to editing Text and we can do it with TextStyle(shadows:['ShadowStyle']); But i don't want to change the source of quill

Any update on this?

**Comment by CatHood0** [comment] 2024-07-20 20:21
Definitely we need to create documentation about custom inline attributes. I'll take care about it
