### ISSUE TITLE
How to add table in flutter quill

### ISSUE THREAD

**Issue by Palimoraihan** [singerdmx/flutter-quill#1822] opened 2024-04-16 06:38 UTC
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How to add some table  flutter quill ?

**Comment by kairan77** [comment] 2024-05-06 06:15
For simple tables with a few columns such as those from latex styled tables in academic papers, you can implement your own using custom embed. They are very easy, just build your own table widget like you build any other flutter widget and include your implementation as an embed passed to the editor.

For complex tables, such as those from excel/word, with dynamic column/cell styling, nested structures, etc, don't even bother.

**Comment by singerdmx** [comment] 2024-06-22 05:23
Duplicate of https://github.com/singerdmx/flutter-quill/issues/1735

**Closed by singerdmx** 2024-06-22 05:23 UTC
Labels: help wanted
