### ISSUE TITLE
UNIDENTIFIED

### ISSUE THREAD

**Issue by SainathChallagundla** [singerdmx/flutter-quill#818] opened 2022-05-18 05:06 UTC
Hi
![QUILL ISSUE](https://user-images.githubusercontent.com/62494401/168960230-2710d741-c596-4e31-8148-8e069b705e25.PNG)

![quilllissues](https://user-images.githubusercontent.com/62494401/168961087-8db67695-2813-421e-9284-01be2aad473a.PNG)

after upgrading 3.0 and flutter_quill 4.2.1  getting these issues.

**Comment by jayjah** [comment] 2022-05-18 06:39
Duplicate of #809

**Closed** 2022-05-18 06:40 UTC
