### ISSUE TITLE
[Mobile] cursor position changes when checking/unchecking the checkbox

### ISSUE THREAD

**Issue by gklamm** [singerdmx/flutter-quill#619] opened 2022-01-26 11:26 UTC
I haven't tried it on iOS, but on Android, the cursor position changes wierdly when checking/unchecking the checkbox.

https://user-images.githubusercontent.com/1202201/151155040-4c52f222-0824-491d-ba87-5633b92a3f15.mp4

**Comment by singerdmx** [comment] 2022-01-26 15:08
![image](https://user-images.githubusercontent.com/122956/151189236-2671323f-54ed-46e2-a409-186b50d3dc05.png)
Issue is from here

**Comment by singerdmx** [comment] 2022-01-27 05:47
@li3317 It seems that selection.extentOffset and selection.documentOffset are both 0 when the issue appears. I guess we need to check why selection got changed.

Below is what is supposed to happen.

![image](https://user-images.githubusercontent.com/122956/151299282-06ecfc66-30b3-4f25-b946-53bc49f63044.png)

**Comment by singerdmx** [comment] 2022-01-31 05:12
the issue is pretty deep in how we merge delta with same styles.
This happens when you have two checkboxes that become either bother checked or unchecked. They merge into one node.

**Comment by singerdmx** [comment] 2022-01-31 05:25
Currently we use attributes `"list": "checked"` and `"list": "unchecked"`.
`list` AttributeScope is BLOCK instead of INLINE

**Comment by singerdmx** [comment] 2022-01-31 06:19
Fixed by https://github.com/singerdmx/flutter-quill/commit/7bd494a3d7ccdbde45a5f6e47ee79c4d7e6f1732

**Closed by singerdmx** 2022-01-31 06:19 UTC

**Comment by singerdmx** [comment] 2022-01-31 07:31
https://youtu.be/k_zB_wiZeUM
