### ISSUE TITLE
How to add table in flutter quill

### ISSUE THREAD

**Issue by Palimoraihan** [singerdmx/flutter-quill#1802] opened 2024-04-05 07:29 UTC
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How i can add some table in flutter quill, and convert the result to html

**Comment by iamlucy18** [comment] 2024-04-12 08:59
+1

**Comment by wudiplk** [comment] 2024-04-15 07:20
+1

**Comment by singerdmx** [comment] 2024-06-22 05:24
Duplicate of https://github.com/singerdmx/flutter-quill/issues/1735

**Closed by singerdmx** 2024-06-22 05:24 UTC
Labels: help wanted
