### ISSUE TITLE
[Mobile & Desktop] Disabling Scroll not working

### ISSUE THREAD

**Issue by matthiasn** [singerdmx/flutter-quill#580] opened 2022-01-08 18:08 UTC
I upgraded to the latest version of this library in [this PR](https://github.com/matthiasn/meins/pull/653) and was having issues when scroll was disabled:

![image](https://user-images.githubusercontent.com/1390808/148654610-269daf92-feb7-49e6-9fb9-315acb3dd173.png)

Enabling scroll in [this commit](https://github.com/matthiasn/meins/pull/653/commits/112e4f520ce91e31fef36bc35910414e0705eeba) fixed the issue for me and isn't a problem in my use case so this issue isn't urgent at all, but others might run into the same issue and don't have to repeat scratching their heads for hours.

**Comment by singerdmx** [comment] 2022-01-08 18:15
Under what specific operation did the error happen?
Did it happen during opening the editor?

**Comment by singerdmx** [comment] 2022-01-08 18:18
This might be easy to figure out since scrollable is only used in two places. My hunch is the first one.
![image](https://user-images.githubusercontent.com/122956/148655177-7991394b-28a1-4e9f-bc36-90656028d714.png)

![image](https://user-images.githubusercontent.com/122956/148655190-5ec8f2d0-fbf9-4aaa-ae96-c74f37deafb7.png)

**Comment by singerdmx** [comment] 2022-01-08 18:20
This may be caused because we introduced maxContentWidth https://github.com/singerdmx/flutter-quill/commit/3fd8aa23dfdedc23aa51ebaf8026982ca08850ee

**Comment by NicolasDionB** [comment] 2022-01-20 19:14
I'm having the same issue. Trying to remove contraints from parent widget does not work. Any idea for a workaround?

I though `maxHeight` was there to actually limit height of the widget.

**Comment by NicolasDionB** [comment] 2022-01-20 19:47
I can confirm it was working fine with 3.0.3, updating to 3.0.4 I get the issue so it's definitely something to do with the changes made adding `maxContentWidth`. Hope this helps.

**Comment by singerdmx** [comment] 2022-01-20 20:53
![image](https://user-images.githubusercontent.com/122956/150420444-67fc9b79-fc66-4d6f-a49e-6222f19a27b5.png)

Should be here

**Comment by NicolasDionB** [comment] 2022-01-20 20:54
I just tested removing the first assert in `performLayout` (if (!constraints.hasBoundedHeight)) and it seems to work, except that the position caret is cropped vertically.

**Comment by singerdmx** [comment] 2022-01-20 20:58
If removing the first assert  is acceptable, you can submit a PR

**Comment by NicolasDionB** [comment] 2022-01-21 18:21
@singerdmx But is it needed when we activate [scrollable]? If so, the condition would have to reflect that and validate it's unbounded only when scrolling is enabled but I'm not sure I see what is the purpose of that check in both cases.

**Comment by singerdmx** [comment] 2022-01-26 15:06
Fixed by https://github.com/singerdmx/flutter-quill/commit/111a249462860686d32d17db398f2f28410f38a7 thanks

**Closed by singerdmx** 2022-01-26 15:06 UTC
Labels: in_progress, next_8
