### ISSUE TITLE
flutter_colorpicker dependency uses removed properties, app won't launch after flutter 3.22.0

### ISSUE THREAD

**Issue by dezsocsete** [singerdmx/flutter-quill#1865] opened 2024-05-14 14:54 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

^9.3.11

### Steps to reproduce

1. Upgrade flutter to 3.22.0
2. flutter create .
3. Add the code sample to the main.dart 

### Expected results

App would run

### Actual results

App does not launch

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: QuillEditor.basic(
        configurations: QuillEditorConfigurations(
          controller: QuillController.basic(),
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
/C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/colorpicker.dart:659:53: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                        Theme.of(context).textTheme.bodyText1,
                                                    ^^^^^^^^^
/C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/colorpicker.dart:669:53: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
                        Theme.of(context).textTheme.bodyText2,
                                                    ^^^^^^^^^
/C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/palette.dart:951:55: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                          Theme.of(context).textTheme.bodyText1,
                                                      ^^^^^^^^^
/C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/palette.dart:960:57: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
                            Theme.of(context).textTheme.bodyText2,
                                                        ^^^^^^^^^
/C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/palette.dart:1042:58: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
          Text('Hex', style: Theme.of(context).textTheme.bodyText1),
                                                         ^^^^^^^^^
/C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/palette.dart:1045:47: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
          width: (Theme.of(context).textTheme.bodyText2?.fontSize ?? 14) * 10,
                                              ^^^^^^^^^

```

</details>

**Comment by mqaa** [comment] 2024-05-14 15:21
The issue is caused by the flutter_colorpicker package. See https://github.com/mchome/flutter_colorpicker/issues/105
This is the error I get when I build by app:

../../../.pub-cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/colorpicker.dart:659:53: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                        Theme.of(context).textTheme.bodyText1,

**Comment by myfknoll** [comment] 2024-05-14 17:57
Same here =/

**Comment by Tanthus** [comment] 2024-05-14 19:11
The fix was published on Github for Colorpicker, was fixed for the master branch but not published   ([ref](https://github.com/mchome/flutter_colorpicker/issues/105)) 

I was able to get my code to compile by adding this temporary fix to my pubspec.yaml file.

```
dependency_overrides:
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master  # or 786d04363f587b818ce585d25b9c2bb62de95aba  

```

**Comment by mqaa** [comment] 2024-05-15 06:26
@Tanthus That does fix the issue for me too. Hope the packages will be updated so no override is required anymore.

**Comment by certainlyWrong** [comment] 2024-05-15 12:45
> The fix was published on Github for Colorpicker, was fixed for the master branch but not published ([ref](https://github.com/mchome/flutter_colorpicker/issues/105))
> 
> I was able to get my code to compile by adding this temporary fix to my pubspec.yaml file.
> 
> ```
> dependency_overrides:
>   flutter_colorpicker:
>     git:
>       url: https://github.com/mchome/flutter_colorpicker
>       ref: master  # or 786d04363f587b818ce585d25b9c2bb62de95aba  
> ```

flutter_colorpick It's a shameful package. I don't even use tags to version the code, flutter_quill can't continue depending on it.

**Comment by rsegecin** [comment] 2024-05-17 04:28
adding the dependency override for `flutter_colorpicker` did make my code run but it lost some color references, like if I wasn't working with material 3 anymore.

**Comment by tbusot** [comment] 2024-05-17 21:05
@rsegecin keep in mind that Material 3 deprecates `background`, `onBackground`, and `surfaceVariants` colors. Pretty major changes unfortunately. Read more here [Introduce new ColorScheme roles for Material 3](https://docs.flutter.dev/release/breaking-changes/new-color-scheme-roles)

**Comment by singerdmx** [comment] 2024-05-18 05:52
should we consider forking `flutter_colorpicker` and publish a new package?

**Comment by myfknoll** [comment] 2024-05-18 06:02
> should we consider forking `flutter_colorpicker` and publish a new package?

Last activity was Apr 5, 2024, so there might be hope. 
But since there are not much contributions in the last year, it would be a good approach.

As a workaround for others, I was forking both repos for now which works temporary:
`  flutter_quill:
    git:
      url: https://github.com/pocketshop-app/flutter-quill
      ref: update`

**Comment by ellet0** [comment] 2024-05-18 17:15
Hi, can you try the latest version now?

**Comment by ellet0** [comment] 2024-05-19 13:34
Fixed in the latest release, flutter_colorpicker package changes has been published

**Closed by ellet0** 2024-05-19 13:34 UTC
Labels: bug
