### ISSUE TITLE
Can't build android windows only

### ISSUE THREAD

**Issue by the-best-is-best** [singerdmx/flutter-quill#1670] opened 2024-01-10 10:47 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.2.2

### Steps to reproduce

when run app build error in windows error but mac is working

### Expected results

Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
Error: Couldn't resolve the package 'build_tool' in 'package:build_tool/build_tool.dart'.
bin/build_tool_runner.dart:1:8: Error: Not found: 'package:build_tool/build_tool.dart'
import 'package:build_tool/build_tool.dart' as build_tool;
       ^
bin/build_tool_runner.dart:3:15: Error: Method not found: 'runMain'.
   build_tool.runMain(args);
              ^^^^^^^
Could not find a command named "bin\build_tool_runner.dill".

### Actual results

  info       Show diagnostic information about the installed tooling.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
2
The system cannot find the path specified.
The system cannot find the file specified.
The system cannot find the file specified.
Cannot operate on packages inside the cache.

### Code sample

Not need when add package in new project and app not run correctly

### Screenshots or Video

![image](https://github.com/singerdmx/flutter-quill/assets/72160249/c5e56af6-7494-431c-b0c2-14c8e7494ff3)

![image](https://github.com/singerdmx/flutter-quill/assets/72160249/34a599c5-65ae-464d-a267-95429d0f0a2b)

**Comment by bkalidasan79** [comment] 2024-01-10 13:52
i'm also face same issue ..

**Comment by ellet0** [comment] 2024-01-15 12:36
Can you try 9.2.5? It doesn't contain any fix for the issue, but the new version of the super clipboard has more error messages and we neer it to debug the bug

**Comment by Til555** [comment] 2024-01-16 08:26
...same here using super_clipboard: ^0.8.3 and flutter_quill: ^9.2.5
![image](https://github.com/singerdmx/flutter-quill/assets/87725898/7e31ef3d-54db-4009-958d-dec877236e1c)

**Comment by ellet0** [comment] 2024-01-16 08:52
> ...same here using super_clipboard: ^0.8.3 and flutter_quill: ^9.2.5 (windows 10, android studio 2023.1.1 Patch 1)
> ![image](https://github.com/singerdmx/flutter-quill/assets/87725898/7e31ef3d-54db-4009-958d-dec877236e1c)
> 

Thanks. Could you provide more info? `flutter run -v`

**Comment by Til555** [comment] 2024-01-16 16:06
thanks a lot for your quick reply ellet0! ...run -v results in a huge list that's too long for the terminal window - so I can only copy and paste the last part (sorry for my ignorance - definitely let me know how to export a proper log if you like). See attached text file -hope this helps :)
[flutterRunV_exported.txt](https://github.com/singerdmx/flutter-quill/files/13952830/flutterRunV_exported.txt)

**Comment by ellet0** [comment] 2024-01-16 16:36
> thanks a lot for your quick reply ellet0! ...run -v results in a huge list that's too long for the terminal window - so I can only copy and paste the last part (sorry for my ignorance - definitely let me know how to export a proper log if you like). See attached text file -hope this helps :) [flutterRunV_exported.txt](https://github.com/singerdmx/flutter-quill/files/13952830/flutterRunV_exported.txt)

You are welcome, can you retry with the latest version? `9.2.6` and if the issue still remain please upload the logs once again using the previous step

**Comment by Til555** [comment] 2024-01-16 17:31
No way - 9.2.6 solved it for me! (well, not all of my issues of course 🤪). But I think every error related to above issue is gone. I even have audio playing once again... Very big HUG ellet0! 🤗 Thank you!

**Comment by ellet0** [comment] 2024-01-16 17:42
> No way - 9.2.6 solved it for me! (well, not all of my issues of course 🤪). But I think every error related to above issue is gone. I even have audio playing once again... Very big HUG ellet0! 🤗 Thank you!

You are welcome, I'm not the one who fixed it

It all thanks to the owner of super clipboard  plugin

**Comment by Til555** [comment] 2024-01-16 19:47
Thank you anyways ellet0! :) ...and another hug to super clipboard plugin owner :D

**Comment by the-best-is-best** [comment] 2024-01-17 10:29
SEVERE: <asynchronous suspension>
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================
use   flutter_quill: ^9.2.6 - super_clipboard: ^0.8.4

**Comment by ellet0** [comment] 2024-01-21 16:22
The issue is now fixed, if you still facing it please let me know

**Closed by ellet0** 2024-01-21 16:22 UTC
Labels: bug

**Comment by the-best-is-best** [comment] 2024-01-21 16:35
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: External Command: rustup "run" "stable" "cargo" "build" "--manifest-path" "C:\Users\MichelleRaouf\AppData\Local\Pub\Cache\hosted\pub.dev\super_native_extensions-0.8.4\rust\Cargo.toml" "-p" "super_native_extensions" "--target" "x86_64-linux-android" "--target-dir" "D:\work\tallem\build\super_native_extensions/build"
SEVERE: Returned Exit Code: 101
SEVERE: --------------------------------------------------------------------------------
SEVERE: STDOUT:
SEVERE: --------------------------------------------------------------------------------
SEVERE: STDERR:
SEVERE: Compiling proc-macro2 v1.0.66
SEVERE:    Compiling unicode-ident v1.0.11
SEVERE:    Compiling memchr v2.5.0
SEVERE:    Compiling libc v0.2.147
SEVERE:    Compiling version_check v0.9.4
SEVERE:    Compiling cfg-if v1.0.0
SEVERE:    Compiling futures-core v0.3.28
SEVERE:    Compiling autocfg v1.1.0
SEVERE:    Compiling regex-syntax v0.7.4
SEVERE:    Compiling log v0.4.19
SEVERE:    Compiling thiserror v1.0.44
SEVERE:    Compiling futures-channel v0.3.28
SEVERE:    Compiling futures-task v0.3.28
SEVERE:    Compiling serde v1.0.183
SEVERE:    Compiling once_cell v1.18.0
SEVERE:    Compiling bytes v1.4.0
SEVERE:    Compiling rustix v0.38.7
SEVERE:    Compiling futures-sink v0.3.28
SEVERE: error: linker `link.exe` not found
SEVERE:   |
SEVERE:   = note: program not found
SEVERE: 
SEVERE: note: the msvc targets depend on the msvc linker but `link.exe` was not found
SEVERE: 
SEVERE: note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.
SEVERE: 
SEVERE: note: VS Code is a different product, and is not sufficient.
SEVERE: 
SEVERE: error: could not compile `futures-task` (build script) due to previous error
SEVERE: warning: build failed, waiting for other jobs to finish...
SEVERE: error: could not compile `futures-channel` (build script) due to previous error
SEVERE: error: could not compile `futures-core` (build script) due to previous error
SEVERE: error: could not compile `thiserror` (build script) due to previous error
SEVERE: error: could not compile `serde` (build script) due to previous error
SEVERE: error: could not compile `memchr` (build script) due to previous error
SEVERE: error: could not compile `proc-macro2` (build script) due to previous error
SEVERE: error: could not compile `libc` (build script) due to previous error
SEVERE: error: could not compile `rustix` (build script) due to previous error
SEVERE: --------------------------------------------------------------------------------
SEVERE: #0      runCommand (package:build_tool/src/util.dart:118:5)
SEVERE: #1      RustBuilder.build (package:build_tool/src/builder.dart:139:5)
SEVERE: <asynchronous suspension>
SEVERE: #2      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:68:25)
SEVERE: <asynchronous suspension>
SEVERE: #3      BuildGradle.build (package:build_tool/src/build_gradle.dart:32:23)
SEVERE: <asynchronous suspension>
SEVERE: #4      BuildGradleCommand.runBuildCommand (package:build_tool/src/build_tool.dart:62:5)
SEVERE: <asynchronous suspension>
SEVERE: #5      BuildCommand.run (package:build_tool/src/build_tool.dart:34:5)
SEVERE: <asynchronous suspension>
SEVERE: #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
SEVERE: <asynchronous suspension>
SEVERE: #7      runMain (package:build_tool/src/build_tool.dart:248:5)
SEVERE: <asynchronous suspension>
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================

**Comment by ellet0** [comment] 2024-01-21 17:47
Did you tried to uninstall rust? the plugin will install pre compiled one with required tools, otherwise you have to install them manually in vs studio

**Comment by the-best-is-best** [comment] 2024-01-21 18:09
Thanks @ellet0 
build success 
thank all for help

**Comment by ellet0** [comment] 2024-01-21 18:10
> Thanks @ellet0 
> build success 
> thank all for help

You are welcome, I'm glad it fixed

**Comment by the-best-is-best** [comment] 2024-01-21 18:25
@ellet0 how use FlutterQuillEmbeds.defaultEditorBuilders(), and active buttons toolbar in last version

**Comment by ellet0** [comment] 2024-01-21 18:28
> @ellet0 how use FlutterQuillEmbeds.defaultEditorBuilders(), and active buttons toolbar in last version 

There are two builders, one for the web and another for other platforms. The default has some logic that runs depending on the platform. It's more limited and less used

Please take a look at the README of flutter quill extensions instead

If you have more questions, please ask them in the discussions so we can focus better at the subject

**Comment by milesegan** [comment] 2024-02-22 00:24
I had the same issue. In my case running `flutter clean` seems to have fixed it.
